/*
 * Turns an audit row ("invoice.cancelled", { ... }) into a sentence a manager
 * can read, and groups actions into a few categories for filtering. Unknown
 * actions still show, humanised, so a newly audited action is never invisible.
 */

export const CATEGORIES = {
  sales:      { label: 'Sales and orders', prefixes: ['invoice', 'order', 'payment', 'table', 'credit_note'] },
  stock:      { label: 'Stock and purchasing', prefixes: ['inventory', 'purchase', 'purchase_order', 'supplier'] },
  menu:       { label: 'Menu and kitchen', prefixes: ['product', 'recipe', 'modifier_group', 'kitchen', 'menu'] },
  money:      { label: 'Expenses and costs', prefixes: ['expense', 'settings'] },
  customers:  { label: 'Customers and offers', prefixes: ['customer', 'coupon', 'loyalty'] },
  team:       { label: 'Team and outlets', prefixes: ['staff', 'outlet'] },
  oversight:  { label: 'Oversight and AI', prefixes: ['leakage', 'ai', 'forecast', 'integration', 'business'] },
  salon:      { label: 'Salon', prefixes: ['salon'] }
};

/** The action prefixes belonging to a category, or null for an unknown one. */
export const prefixesFor = (category) => CATEGORIES[category]?.prefixes ?? null;

export const categoryOf = (action) => {
  const prefix = String(action).split('.')[0];
  return Object.entries(CATEGORIES).find(([, c]) => c.prefixes.includes(prefix))?.[0] ?? 'other';
};

const money = (n) => (typeof n === 'number' ? `₹${n.toLocaleString('en-IN')}` : null);
const join = (...parts) => parts.filter(Boolean).join(' ');

/* Each: (metadata, target) -> sentence. `target` is the readable name of the thing acted on, when known. */
const SENTENCES = {
  'invoice.created': (m, t) => join('Billed', t || 'a sale', m.total != null && `for ${money(m.total)}`),
  'invoice.cancelled': (m, t) => join('Cancelled', t || 'an invoice'),
  'invoice.refunded': (m, t) => join('Refunded', money(m.amount), t && `on ${t}`, m.reason && `(${m.reason})`),
  'credit_note.issued': (m, t) => join('Issued credit note', t, m.total != null && `for ${money(m.total)}`, m.refunded > 0 && `(refunded ${money(m.refunded)})`, m.restocked && '(returned to stock)'),
  'payment.recorded': (m, t) => join('Recorded a payment of', money(m.amount), t && `on ${t}`),
  'order.opened': (m, t) => join('Opened', t || 'an order'),
  'order.kot_sent': (m, t) => join('Sent', t || 'an order', 'to the kitchen', m.items != null && `(${m.items} item${m.items === 1 ? '' : 's'})`),
  'order.billed': (m, t) => join('Billed', t || 'an order', m.partial && '(part of the tab)'),
  'order.cancelled': (m, t) => join('Cancelled', t || 'an order'),
  'order.transferred': (m, t) => join('Moved', t || 'an order', 'to another table'),
  'order.merged': (m, t) => join('Merged another order into', t || 'an order'),
  'order.split': (m, t) => join('Split', t || 'an order', 'between tables'),
  'order.placed_by_customer': (m, t) => join('Customer ordered from their table', t && `(${t})`),
  'reservation.created': (m) => join('Booked a table for', m.guest, m.party && `(party of ${m.party})`),
  'reservation.updated': (m, t) => join('Changed reservation', t),
  'reservation.cancelled': (m) => join('Cancelled the reservation for', m.guest),
  'reservation.no_show': (m) => join('Marked', m.guest, 'as a no-show'),
  'reservation.completed': (m) => join('Completed the reservation for', m.guest),
  'reservation.seated': (m) => join('Seated', m.guest, m.table && `at ${m.table}`),
  'waitlist.added': (m) => join('Added', m.guest, 'to the waitlist', m.party && `(party of ${m.party})`),
  'waitlist.seated': (m) => join('Seated', m.guest, 'from the waitlist', m.table && `at ${m.table}`),
  'combo.set': (m, t) => join('Made', t || 'an item', 'a combo', m.items && `of ${m.items} items`),
  'combo.cleared': (m, t) => join('Turned', t || 'a combo', 'back into a single item'),
  'order.waiter_set': (m, t) => join('Changed the waiter on', t || 'an order'),
  'messaging.settings_updated': () => 'Changed the customer messaging settings',
  'messaging.bill_sent': (m, t) => join('Sent', t || 'a bill', 'to the customer', m.status && `(${String(m.status).toLowerCase()})`),
  'messaging.campaign_sent': (m) => join('Sent an offer to', m.recipients, m.recipients === 1 ? 'customer' : 'customers'),
  'customer.marketing_opt_out': (m, t) => join(m.opt_out ? 'Stopped offers to' : 'Resumed offers to', t || 'a customer'),
  'points.program_updated': (m) => join(m.enabled ? 'Updated' : 'Switched off', 'the loyalty points scheme'),
  'points.adjusted': (m, t) => join(m.points > 0 ? 'Gave' : 'Took', Math.abs(m.points), 'loyalty points', m.points > 0 ? 'to' : 'from', t || 'a customer', m.note && `(${m.note})`),
  'recipe.outlet_cleared': (m, t) => join('Removed the outlet recipe for', t || 'a dish', '(back to the default)'),
  'purchase_order.part_received': (m, t) => join('Received part of purchase order', t, m.short?.length && `(still owed: ${m.short.join(', ')})`),
  'purchase_order.closed_short': (m, t) => join('Closed purchase order', t, 'as short: the rest is not coming'),
  'supplier.prices_set': (m, t) => join('Updated the price list of', t || 'a supplier', m.count && `(${m.count} price${m.count === 1 ? '' : 's'})`),
  'debit_note.issued': (m, t) => join('Issued debit note', t, m.total != null && `for ${money(m.total)}`, m.kind === 'RETURN' ? '(goods returned)' : '(price correction)'),
  'transfer_request.created': (m) => join('Asked another outlet for', m.items, m.items === 1 ? 'item' : 'items'),
  'transfer_request.fulfilled': (m) => join('Sent stock for a request', m.status === 'PARTIAL' && '(in part)'),
  'transfer_request.rejected': (m) => join('Turned down a stock request', m.reason && `(${m.reason})`),
  'transfer_request.cancelled': () => 'Called off a stock request',
  'gst.settings_updated': () => 'Changed the GST filing settings',
  'gst.gstr1_exported': (m) => join('Downloaded the GSTR-1 file', m.warnings > 0 && `(${m.warnings} warning${m.warnings === 1 ? '' : 's'})`),
  'gst.irn_recorded': (m, t) => join('Recorded the IRN for', t || 'an invoice'),
  'gst.eway_recorded': (m, t) => join('Recorded the e-way bill for', t || 'an invoice'),
  'user.two_factor_enabled': () => 'Turned on two-step verification',
  'user.two_factor_disabled': () => 'Turned off two-step verification',
  'user.recovery_code_used': (m) => join('Signed in with a recovery code', m.left != null && `(${m.left} left)`),
  'user.password_changed': () => 'Changed their password',
  'user.signed_out_everywhere': () => 'Signed out of every device',
  'security.policy_updated': (m) => join(m.require_2fa_admins ? 'Required' : 'No longer requires', 'two-step verification for owners and admins'),
  'table.updated': (m, t) => join('Changed', t || 'a table'),
  'inventory.adjusted': (m, t) => join('Adjusted stock of', t || 'an item', m.quantity != null && `by ${m.quantity}`, m.reason && `(${m.reason})`),
  'inventory.wastage': (m, t) => join('Logged wastage of', m.quantity, 'of', t || 'an item', m.reason_code && `(${String(m.reason_code).toLowerCase()})`),
  'inventory.transferred': (m, t) => join('Transferred', m.quantity, 'of', t || 'an item', 'between outlets'),
  'purchase.created': (m, t) => join('Recorded purchase', t, m.total != null && `of ${money(m.total)}`),
  'purchase_order.drafted': (m, t) => join('Drafted purchase order', t, m.source === 'FORECAST' && 'from the forecast'),
  'purchase_order.updated': (m, t) => join('Edited purchase order', t),
  'purchase_order.sent': (m, t) => join('Sent purchase order', t, 'to the supplier', m.emailed && '(emailed)'),
  'purchase_order.received': (m, t) => join('Received purchase order', t, m.total != null && `worth ${money(m.total)}`, m.short?.length && `(short: ${m.short.join(', ')})`),
  'purchase_order.cancelled': (m, t) => join('Cancelled purchase order', t),
  'supplier.created': (m, t) => join('Added supplier', t),
  'supplier.updated': (m, t) => join('Edited supplier', t),
  'menu.imported': (m) => join('Imported the menu from a photo:', m.created != null && `${m.created} added`, m.updated > 0 && `${m.updated} prices updated`, m.skipped > 0 && `${m.skipped} skipped`),
  'product.created': (m, t) => join('Added', t || 'a product'),
  'product.updated': (m, t) => join('Edited', t || 'a product', m.fields?.length && `(${m.fields.join(', ')})`),
  'product.archived': (m, t) => join('Archived', t || 'a product'),
  'product.image_uploaded': (m, t) => join('Uploaded a photo for', t || 'a product'),
  'product.modifiers_set': (m, t) => join('Changed the options on', t || 'a product'),
  'product.outlet_settings': (m, t) => join('Changed the price or availability of', t || 'a product', 'at an outlet'),
  'recipe.updated': (m, t) => join('Changed the recipe of', t || 'a dish'),
  'modifier_group.created': (m, t) => join('Added an option group', t),
  'modifier_group.updated': (m, t) => join('Edited an option group', t),
  'kitchen.rush': (m, t) => join('Marked', t || 'an order', 'rush'),
  'kitchen.station_created': () => 'Added a kitchen station',
  'kitchen.station_updated': () => 'Changed a kitchen station',
  'kitchen.routing_updated': () => 'Changed which station cooks which dish',
  'expense.created': (m, t) => join('Recorded an expense', t),
  'expense.updated': (m, t) => join('Edited an expense', t),
  'expense.deleted': (m, t) => join('Deleted an expense', t),
  'settings.costs_updated': () => 'Changed the cost assumptions used for profit',
  'business.updated': (m) => join('Changed business settings', m.fields?.length && `(${m.fields.join(', ')})`),
  'business.created': () => 'Created the business',
  'customer.created': (m, t) => join('Added customer', t),
  'customer.updated': (m, t) => join('Edited customer', t),
  'coupon.created': (m) => join('Created coupon', m.code),
  'coupon.updated': (m) => join('Changed a coupon', m.length && `(${m.join?.(', ')})`),
  'loyalty.program_updated': (m) => join('Changed the loyalty program', m.enabled === false && '(switched off)', m.enabled === true && '(on)'),
  'staff.added': (m, t) => join('Added', t || 'a person', m.role && `as ${String(m.role).toLowerCase().replace('_', ' ')}`),
  'staff.updated': (m, t) => join('Changed', t || 'a person', m.role && `to ${String(m.role).toLowerCase().replace('_', ' ')}`, m.status === 'DISABLED' && '(access disabled)'),
  'staff.permissions_updated': (m, t) => join('Changed the permissions of', t || 'a person', m.changes && `(${Object.entries(m.changes).map(([k, v]) => `${k}: ${v}`).join(', ')})`),
  'outlet.created': (m) => join('Opened outlet', m.name),
  'outlet.updated': () => 'Edited an outlet',
  'outlet.closed': () => 'Closed an outlet',
  'outlet.reopened': () => 'Reopened an outlet',
  'leakage.reviewed': (m) => join('Reviewed a leakage finding', m.status && `(${String(m.status).toLowerCase()})`),
  'forecast.event_added': (m) => join('Added a demand event', m.label && `“${m.label}”`),
  'forecast.event_removed': () => 'Removed a demand event',
  'integration.updated': (m, t) => join('Changed the', t || 'delivery', 'integration'),
  'integration.menu_synced': (m, t) => join('Synced the menu to', t || 'a delivery platform'),
  // salon
  'salon.sale_completed': (m, t) => join('Billed', t || 'a salon sale', m.total != null && `for ${money(m.total)}`, m.offers?.length && `(offers: ${m.offers.join(', ')})`),
  'salon.price_changed': (m) => join('Changed the price of', m.name, m.before?.price != null && `from ${money(m.before.price)}`, m.after?.price != null && `to ${money(m.after.price)}`),
  'salon.service_created': (m) => join('Added the service', m.after?.name && `“${m.after.name}”`),
  'salon.service_updated': (m, t) => join('Edited the service', t),
  'salon.service_archived': (m) => join('Archived the service', m.name),
  'salon.service_restored': (m) => join('Restored the service', m.name),
  'salon.service_consumables_changed': (m) => join('Changed the consumables used by', m.name || 'a service'),
  'salon.product_details_changed': (m) => join('Changed the salon details of', m.name),
  'salon.settings_changed': () => 'Changed the salon settings',
  'salon.branch_settings_changed': (m, t) => join('Changed the hours of', t || 'an outlet'),
  'salon.appointment_created': (m) => join('Booked an appointment', m.services != null && `(${m.services} service${m.services === 1 ? '' : 's'})`),
  'salon.appointment_rescheduled': () => 'Moved an appointment',
  'salon.appointment_status': (m) => join('Marked an appointment', m.after?.status && String(m.after.status).toLowerCase().replace('_', ' '), m.reason && `(${m.reason})`),
  'salon.staff_created': (m) => join('Added', m.after?.name, 'to the salon team'),
  'salon.staff_updated': (m, t) => join('Edited the team member', t),
  'salon.commission_rate_changed': (m, t) => join('Changed the commission rate for', t || m.name),
  'salon.commission_approved': (m) => join('Approved', money(m.after?.total), 'commission for', m.staff),
  'salon.commission_paid': (m) => join('Paid', money(m.after?.total), 'commission to', m.staff),
  'salon.attendance_marked': (m) => join('Marked', m.name, m.after?.status && String(m.after.status).toLowerCase().replace('_', ' ')),
  'salon.client_created': (m) => join('Added the client', m.after?.name),
  'salon.client_updated': (m, t) => join('Edited the client', t),
  'salon.client_note_added': (m, t) => join('Added a private note on', t || 'a client'),
  'salon.loyalty_rules_changed': () => 'Changed the salon loyalty rules',
  'salon.points_expired': (m) => join('Expired', m.after?.points, 'loyalty points'),
  'salon.membership_plan_created': (m) => join('Created the membership plan', m.after?.name),
  'salon.membership_plan_changed': () => 'Changed a membership plan',
  'salon.membership_sold': (m) => join('Sold', m.count, m.count === 1 ? 'membership' : 'memberships'),
  'salon.membership_cancelled': (m) => join('Cancelled a', m.plan, 'membership', m.reason && `(${m.reason})`),
  'salon.package_created': (m) => join('Created the package', m.after?.name),
  'salon.package_changed': () => 'Changed a package',
  'salon.package_sold': (m) => join('Sold', m.count, m.count === 1 ? 'package' : 'packages'),
  'salon.package_adjusted': (m) => join('Adjusted a client package', m.reason && `(${m.reason})`),
  'salon.gift_card_issued_free': (m) => join('Issued a free gift card of', money(m.after?.amount), m.reason && `(${m.reason})`),
  'salon.gift_card_adjusted': (m) => join('Changed a gift card balance from', money(m.before?.balance), 'to', money(m.after?.balance), m.reason && `(${m.reason})`),
  'salon.gift_card_cancelled': (m) => join('Cancelled a gift card', m.reason && `(${m.reason})`),
  'salon.offer_created': (m) => join('Created the offer', m.after?.name),
  'salon.offer_changed': () => 'Changed an offer',
  'salon.stock_in': (m) => join('Added', m.after?.quantity, 'to', m.name || 'stock', m.after?.batch_no && `(batch ${m.after.batch_no})`),
  'salon.automation_changed': (m, t) => join('Changed the', t || 'salon', 'automation'),
  'salon.campaign_sent': (m) => join('Sent a campaign to', m.recipients, m.recipients === 1 ? 'client' : 'clients'),
  'ai.asked': () => 'Asked Flow AI a question',
  'ai.enabled': () => 'Turned Flow AI on',
  'ai.disabled': () => 'Turned Flow AI off'
};

export const describeAction = (action, metadata = {}, target = null) => {
  const make = SENTENCES[action];
  if (make) { try { return make(metadata || {}, target); } catch { /* fall through to the plain version */ } }
  const [thing, verb] = String(action).split('.');
  return `${verb ? verb.replace(/_/g, ' ') : 'did'} ${thing.replace(/_/g, ' ')}${target ? ` ${target}` : ''}`.replace(/^./, (c) => c.toUpperCase());
};

/** How to look up a readable name for the thing an audit row is about. */
export const TARGETS = {
  credit_note: { table: 'credit_notes', id: 'cn_id', name: "'Credit note ' || cn_number" },
  invoice: { table: 'invoices', id: 'invoice_id', name: "'Invoice ' || invoice_number" },
  order: { table: 'orders', id: 'order_id', name: 'order_number' },
  purchase_order: { table: 'purchase_orders', id: 'po_id', name: 'po_number' },
  product: { table: 'products', id: 'product_id', name: 'name' },
  customer: { table: 'customers', id: 'customer_id', name: 'name' },
  coupon: { table: 'coupons', id: 'coupon_id', name: 'code' },
  user: { table: 'users', id: 'user_id', name: 'name' },
  branch: { table: 'branches', id: 'branch_id', name: 'name' },
  supplier: { table: 'suppliers', id: 'supplier_id', name: 'name' },
  salon_staff: { table: 'salon_staff', id: 'staff_id', name: 'name' },
  salon_appointment: { table: 'salon_appointments', id: 'appointment_id', name: "'Appointment #' || appointment_id" },
  gift_card: { table: 'salon_gift_cards', id: 'card_id', name: 'code' }
};
