/*
 * Languages. The app is written in English; every shared component (buttons, titles, list rows, chips, hints) passes its text through t(),
 * which returns the Hindi when the person chose Hindi and the text is in the dictionary, and the English otherwise. So a missing translation
 * shows English, never a blank or a key. `{name}` in a text is filled from the second argument. The choice is remembered on the phone.
 */
import { createStore, useStore } from './store.ts';

export type Lang = 'en' | 'hi' | 'ta' | 'te' | 'kn' | 'mr' | 'bn' | 'gu';
/* Each language is written in itself. Only the ones with a dictionary below are translated; the others are offered now and show English
   until their words are added (add a dictionary to DICTS and set ready). */
export const LANGS: { id: Lang; label: string }[] = [
  { id: 'en', label: 'English' }, { id: 'hi', label: 'हिन्दी' }, { id: 'ta', label: 'தமிழ்' }, { id: 'te', label: 'తెలుగు' },
  { id: 'kn', label: 'ಕನ್ನಡ' }, { id: 'mr', label: 'मराठी' }, { id: 'bn', label: 'বাংলা' }, { id: 'gu', label: 'ગુજરાતી' }
];
export const isTranslated = (lang: Lang): boolean => lang === 'en' || lang in DICTS;

const store = createStore<{ lang: Lang }>({ lang: 'en' });
export const getLang = (): Lang => store.get().lang;
export const setLangValue = (lang: Lang) => store.set({ lang });
export const useLang = (): Lang => useStore(store).lang;

export const fill = (text: string, vars?: Record<string, string | number>): string => (vars ? text.replace(/\{(\w+)\}/g, (_, k: string) => (k in vars ? String(vars[k]) : `{${k}}`)) : text);

export const t = (text: string, vars?: Record<string, string | number>): string => fill(DICTS[store.get().lang]?.[text] ?? text, vars);

/** Text that may be a plain string (translate it) or anything else (leave it). */
export const tx = <T,>(v: T): T => (typeof v === 'string' ? (t(v) as unknown as T) : v);

export const HI: Record<string, string> = {
  // tabs and places
  'Home': 'होम', 'Sell': 'बिक्री', 'Tables': 'टेबल', 'Bills': 'बिल', 'Products': 'प्रोडक्ट', 'More': 'और',
  'Customers': 'ग्राहक', 'Stock': 'स्टॉक', 'Reports': 'रिपोर्ट', 'Settings': 'सेटिंग्स', 'Help': 'मदद', 'Kitchen': 'किचन',
  'Kitchen screen': 'किचन स्क्रीन', 'Bills on hold': 'होल्ड पर बिल', 'Bills waiting to send': 'भेजने के इंतज़ार में बिल',
  // buttons
  'Back': 'पीछे', 'Cancel': 'रद्द करें', 'Done': 'हो गया', 'Next': 'आगे', 'Not now': 'अभी नहीं', 'Try again': 'फिर कोशिश करें', 'Got it': 'समझ गया',
  'Scan': 'स्कैन', 'Hold': 'होल्ड', 'Hold bill': 'बिल होल्ड करें', 'Clear bill': 'बिल साफ़ करें', 'Take payment': 'पेमेंट लें', 'New bill': 'नया बिल',
  'Resume': 'जारी रखें', 'Discard': 'हटाएँ', 'Rush': 'जल्दी', 'Mark served': 'परोसा गया', 'Add items': 'आइटम जोड़ें', 'Bill and pay': 'बिल बनाएँ और पेमेंट लें',
  'Add customer': 'ग्राहक जोड़ें', 'Add product': 'प्रोडक्ट जोड़ें', 'Save customer': 'ग्राहक सेव करें', 'Save product': 'प्रोडक्ट सेव करें', 'Save price': 'कीमत सेव करें',
  'Update stock': 'स्टॉक अपडेट करें', 'Remove this product': 'यह प्रोडक्ट हटाएँ', 'Start a bill': 'बिल शुरू करें', 'Call': 'कॉल करें', 'Send now': 'अभी भेजें',
  'Send waiting bills now': 'इंतज़ार वाले बिल अभी भेजें', 'Print a test receipt': 'टेस्ट रसीद छापें', 'Print the bill': 'बिल छापें',
  'Share the bill': 'बिल शेयर करें', 'Sign out': 'साइन आउट', 'Allow the camera': 'कैमरा की अनुमति दें', 'Download now': 'अभी डाउनलोड करें', 'Takeaway order': 'टेकअवे ऑर्डर',
  'Back to the menu': 'मेन्यू पर वापस', 'Back to the bill': 'बिल पर वापस', 'Make my first bill': 'मेरा पहला बिल बनाएँ', 'Open flowxp.in': 'flowxp.in खोलें',
  'Watch the one-minute tour again': 'एक मिनट का टूर फिर देखें', 'Show the tips and checklist again': 'टिप्स और चेकलिस्ट फिर दिखाएँ', 'Next customer: new bill': 'अगला ग्राहक: नया बिल',
  "Clear this phone's data": 'इस फ़ोन का डेटा साफ़ करें', 'Send a test report to FlowXP': 'FlowXP को टेस्ट रिपोर्ट भेजें', 'Sign in': 'साइन इन', 'Continue': 'जारी रखें', 'Forgot your password?': 'पासवर्ड भूल गए?',
  'Show': 'दिखाएँ', 'Hide': 'छिपाएँ', 'Back to the tables': 'टेबल पर वापस', 'Cancel this item': 'यह आइटम रद्द करें', 'Send to the kitchen / barista': 'किचन / बरिस्ता को भेजें',
  // fields and placeholders
  'Search or scan a barcode': 'खोजें या बारकोड स्कैन करें', 'Search by name or barcode': 'नाम या बारकोड से खोजें', 'Search by name or phone': 'नाम या फ़ोन से खोजें',
  'Search the menu': 'मेन्यू में खोजें', 'Bill number, customer or phone': 'बिल नंबर, ग्राहक या फ़ोन', 'Name': 'नाम', 'Email': 'ईमेल', 'Email (optional)': 'ईमेल (वैकल्पिक)',
  'Password': 'पासवर्ड', 'Mobile number': 'मोबाइल नंबर', 'Selling price': 'बिक्री कीमत', 'MRP (optional)': 'MRP (वैकल्पिक)', 'Barcode': 'बारकोड', 'Barcode (optional)': 'बारकोड (वैकल्पिक)',
  '6-digit code': '6 अंकों का कोड', 'For example: Ravi': 'जैसे: रवि', 'Unit (pc, kg, litre)': 'इकाई (नग, किलो, लीटर)', 'How many (10 or -3)': 'कितने (10 या -3)',
  'How many do you have now?': 'अभी आपके पास कितने हैं?', 'Why (counted, damaged, received…)': 'क्यों (गिनती, खराब, प्राप्त…)', 'UPI reference (optional)': 'UPI रेफ़रेंस (वैकल्पिक)',
  'Slip or approval number (optional)': 'स्लिप या अप्रूवल नंबर (वैकल्पिक)', 'Cash received (optional)': 'मिली नकद राशि (वैकल्पिक)',
  // labels
  'Today': 'आज', "Today's sales": 'आज की बिक्री', 'Bills today': 'आज के बिल', 'Still to be paid': 'अभी चुकाना बाकी', 'Low on stock': 'स्टॉक कम', 'Still owed': 'बाकी रक़म',
  'Average bill': 'औसत बिल', 'Billed': 'कुल बिल', 'GST in it': 'इसमें GST', 'Best day': 'सबसे अच्छा दिन', 'Busiest hour': 'सबसे व्यस्त घंटा', 'Owes you': 'आपको देना है',
  'Bought so far': 'अब तक की ख़रीद', 'Last bill': 'आख़िरी बिल', 'Cost price': 'ख़रीद कीमत', 'In stock here': 'यहाँ स्टॉक में', 'Customer': 'ग्राहक', 'Business': 'व्यापार',
  'Outlet': 'आउटलेट', 'Server': 'सर्वर', 'App version': 'ऐप वर्ज़न', 'Phone code': 'फ़ोन कोड', 'Signed in as': 'साइन इन', 'Products on this phone': 'इस फ़ोन पर प्रोडक्ट',
  'Products last updated': 'प्रोडक्ट आख़िरी बार अपडेट', 'Bills waiting / need a decision': 'इंतज़ार में / फ़ैसला चाहिए', 'Late': 'देर', 'Oldest': 'सबसे पुराना', 'Ready': 'तैयार',
  'To make': 'बनाना है', 'Items': 'आइटम', 'Category': 'श्रेणी', 'GST rate': 'GST दर', 'Sales': 'बिक्री',
  // list rows
  'How much you sold, and what sells best': 'कितनी बिक्री हुई, और क्या सबसे ज़्यादा बिकता है', 'How to do things, and the quick tour': 'काम कैसे करें, और छोटा टूर',
  'Made without internet, and recent': 'बिना इंटरनेट के बने, और हाल के', 'Printer, updates, this phone': 'प्रिंटर, अपडेट, यह फ़ोन', 'Resume or discard': 'जारी रखें या हटाएँ',
  'The menu: prices, stock, add an item': 'मेन्यू: कीमत, स्टॉक, नया आइटम', 'Their bills, and what they still owe': 'उनके बिल, और कितना बाकी है',
  'What is running low, and fix a count': 'क्या कम है, और गिनती ठीक करें', 'What to make, what is ready to serve': 'क्या बनाना है, क्या परोसने को तैयार है', 'Switch outlet': 'आउटलेट बदलें',
  // section titles
  'Shop': 'दुकान', 'This phone': 'यह फ़ोन', 'Account': 'खाता', 'How do I…': 'मैं कैसे…', 'Learning the app': 'ऐप सीखें', 'Still stuck?': 'अभी भी अटके हैं?',
  'Best sellers': 'सबसे ज़्यादा बिकने वाले', 'Best sellers this week': 'इस हफ़्ते सबसे ज़्यादा बिके', 'Latest bills': 'ताज़ा बिल', 'Recent bills': 'हाल के बिल', 'How it was paid': 'भुगतान कैसे हुआ',
  'By category': 'श्रेणी के अनुसार', 'Day by day': 'दिन-दिन', 'Where the sales came from': 'बिक्री कहाँ से आई', 'Change the price': 'कीमत बदलें', 'Correct the stock': 'स्टॉक ठीक करें',
  'Takeaway and delivery, open now': 'टेकअवे और डिलीवरी, अभी खुले', 'New customer': 'नया ग्राहक', 'New product': 'नया प्रोडक्ट', 'Where are you billing?': 'आप कहाँ बिल बना रहे हैं?',
  'Updates by itself': 'अपने आप अपडेट होता है', 'Token to call out': 'बुलाने के लिए टोकन', 'Checking camera…': 'कैमरा जाँच रहे हैं…',
  // messages
  'No bills yet.': 'अभी कोई बिल नहीं।', 'No payments in this period.': 'इस अवधि में कोई भुगतान नहीं।', 'No sales in this period.': 'इस अवधि में कोई बिक्री नहीं।', 'No sales yet this week.': 'इस हफ़्ते अभी कोई बिक्री नहीं।',
  'No bills on hold. Hold one from the till when a customer steps away.': 'कोई बिल होल्ड पर नहीं है। ग्राहक के हटने पर बिक्री स्क्रीन से बिल होल्ड करें।',
  'No products on this phone yet. Connect once so they can be downloaded.': 'इस फ़ोन पर अभी प्रोडक्ट नहीं हैं। एक बार इंटरनेट से जुड़ें ताकि वे डाउनलोड हो सकें।',
  'Today\'s figures are shown to people allowed to see reports.': 'आज के आँकड़े केवल रिपोर्ट देखने की अनुमति वाले लोगों को दिखते हैं।',
  'Give it a name to find it later, like a person or a table.': 'बाद में ढूँढने के लिए नाम दें, जैसे किसी का नाम या टेबल।',
  'This bill is empty': 'यह बिल खाली है', 'Tap an item on the Menu, search above, or tap Scan to read a barcode.': 'मेन्यू में किसी आइटम पर टैप करें, ऊपर खोजें, या बारकोड पढ़ने के लिए स्कैन दबाएँ।',
  'Visit the FlowXP website for guides and to contact us.': 'गाइड और संपर्क के लिए FlowXP वेबसाइट देखें।',
  'Done. The tips will appear again as you use each screen.': 'हो गया। हर स्क्रीन इस्तेमाल करते समय टिप्स फिर दिखेंगी।',
  'No internet. You can keep billing': 'इंटरनेट नहीं है। आप बिल बनाते रह सकते हैं', 'All bills sent': 'सारे बिल भेजे जा चुके हैं', 'FlowXP is not answering. You can keep billing': 'FlowXP जवाब नहीं दे रहा। आप बिल बनाते रह सकते हैं',
  'Sent': 'भेजा गया', 'FlowXP could not accept it': 'FlowXP ने इसे स्वीकार नहीं किया', 'Waiting to send': 'भेजने का इंतज़ार', 'Waiting for the internet.': 'इंटरनेट का इंतज़ार।',
  'Bill saved on this phone': 'बिल इस फ़ोन पर सेव हुआ', 'Bill made': 'बिल बन गया',
  'No internet. Check your connection and try again.': 'इंटरनेट नहीं है। कनेक्शन जाँचकर फिर कोशिश करें।',
  'No internet. Showing what was saved {when}.': 'इंटरनेट नहीं है। {when} सेव किया हुआ दिखा रहे हैं।', 'Loading': 'लोड हो रहा है', 'Loading bills': 'बिल लोड हो रहे हैं',
  'Loading customers': 'ग्राहक लोड हो रहे हैं', 'Loading the product': 'प्रोडक्ट लोड हो रहा है', 'Loading the order': 'ऑर्डर लोड हो रहा है', 'Loading tickets': 'टिकट लोड हो रहे हैं',
  'Loading held bills': 'होल्ड बिल लोड हो रहे हैं', 'Loading the floor': 'फ़्लोर लोड हो रहा है', "Loading today's figures": 'आज के आँकड़े लोड हो रहे हैं',
  '{done} of {total}': '{total} में से {done}', '{at} of {total}': '{total} में से {at}', 'Skip': 'छोड़ें',
  'Tap what you want to do.': 'जो करना है उस पर टैप करें।',
  'Offer': 'ऑफ़र', 'Menu': 'मेन्यू', 'Bill': 'बिल', 'See': 'देखें', 'sign in again': 'फिर साइन इन करें', 'no internet': 'इंटरनेट नहीं',
  '{n} item · GST {gst}': '{n} आइटम · GST {gst}', '{n} items · GST {gst}': '{n} आइटम · GST {gst}', 'Clear this bill?': 'यह बिल साफ़ करें?', 'All {n} items will be removed.': 'सभी {n} आइटम हट जाएँगे।',
  'Keep the bill': 'बिल रखें', 'Customer: {name}. Tap to remove.': 'ग्राहक: {name}। हटाने के लिए टैप करें।', 'Hold this bill': 'यह बिल होल्ड करें', '{n} bill needs a decision': '{n} बिल पर फ़ैसला चाहिए', '{n} bills need a decision': '{n} बिलों पर फ़ैसला चाहिए', '{n} bill waiting to send': '{n} बिल भेजने के इंतज़ार में', '{n} bills waiting to send': '{n} बिल भेजने के इंतज़ार में',
  'Good morning': 'सुप्रभात', 'Good afternoon': 'नमस्कार', 'Good evening': 'शुभ संध्या', 'Last {n} days': 'पिछले {n} दिन',
  'Open your authenticator app and type the 6-digit code for FlowXP. Lost your phone? Type a recovery code instead.': 'अपना ऑथेंटिकेटर ऐप खोलें और FlowXP का 6 अंकों का कोड लिखें। फ़ोन खो गया? इसकी जगह रिकवरी कोड लिखें।',
  'Refresh the product list': 'प्रोडक्ट सूची रीफ़्रेश करें',
  '{n} changes need a decision': '{n} बदलावों पर फ़ैसला चाहिए', '{n} changes waiting to send': '{n} बदलाव भेजने के इंतज़ार में', 'Changes waiting to send': 'भेजने के इंतज़ार में बदलाव',
  // language
  'Language': 'भाषा', 'Choose the language the app is shown in.': 'ऐप किस भाषा में दिखे, चुनें।',
  // sign in
  'Sign in with the email and password you use on flowxp.in.': 'flowxp.in पर इस्तेमाल होने वाले ईमेल और पासवर्ड से साइन इन करें।',
  'Your sign-in stays on this phone, in its secure storage.': 'आपका साइन-इन इस फ़ोन की सुरक्षित स्टोरेज में रहता है।',
  // hints
  'Making a bill': 'बिल बनाना', 'Tap an item to add it. Tap Bill to check it, then Take payment. The total shown is about right: the exact amount is worked out when you pay.': 'आइटम पर टैप करके जोड़ें। जाँचने के लिए बिल दबाएँ, फिर पेमेंट लें। दिखाया गया टोटल लगभग सही है; सही रक़म पेमेंट के समय तय होती है।',
  'No internet? Keep billing': 'इंटरनेट नहीं? बिल बनाते रहें', 'Bills are saved on this phone and sent to FlowXP by themselves when the signal is back. You do not need to do anything.': 'बिल इस फ़ोन पर सेव होते हैं और इंटरनेट आने पर अपने आप FlowXP को भेज दिए जाते हैं। आपको कुछ नहीं करना है।',
  'Tap a free table to start an order. Tap a busy one to add items, send them to the kitchen, or bill.': 'ऑर्डर शुरू करने के लिए खाली टेबल पर टैप करें। भरी टेबल पर आइटम जोड़ें, किचन को भेजें, या बिल बनाएँ।',
  'An order': 'एक ऑर्डर', 'Add items, then Send to kitchen. When the food is ready, mark it served. Bill and pay when the table is done.': 'आइटम जोड़ें, फिर किचन को भेजें। खाना तैयार होने पर परोसा गया चिह्नित करें। टेबल पूरी होने पर बिल बनाएँ।',
  'Tap a product to change its price or fix its stock. Add product is for something new.': 'कीमत बदलने या स्टॉक ठीक करने के लिए प्रोडक्ट पर टैप करें। नई चीज़ के लिए प्रोडक्ट जोड़ें दबाएँ।',
  'Tap a dish when it is done. Rush puts a table first. Undo stays on screen for a few seconds after every tap.': 'डिश तैयार होने पर उस पर टैप करें। जल्दी दबाने से वह टेबल सबसे पहले आती है। हर टैप के बाद कुछ सेकंड के लिए वापस का बटन रहता है।',
  // tour
  'Make a bill in three taps': 'तीन टैप में बिल बनाएँ', 'Tap the items.': 'आइटम पर टैप करें।', 'Tap Take payment.': 'पेमेंट लें दबाएँ।', 'Hand over the bill.': 'बिल ग्राहक को दें।',
  'No internet? Keep selling': 'इंटरनेट नहीं? बिक्री जारी रखें', 'Bills are saved on this phone.': 'बिल इस फ़ोन पर सेव होते हैं।', 'They are sent by themselves when the signal returns.': 'इंटरनेट लौटने पर वे अपने आप भेज दिए जाते हैं।',
  'Tables and the kitchen': 'टेबल और किचन', 'Open a table, add items, send to the kitchen.': 'टेबल खोलें, आइटम जोड़ें, किचन को भेजें।', 'Cooks tap a dish when it is ready. You see it here.': 'कुक डिश तैयार होने पर टैप करते हैं। आप उसे यहाँ देखते हैं।',
  'Everything else is under More': 'बाकी सब "और" में है', 'Products, customers, stock and reports.': 'प्रोडक्ट, ग्राहक, स्टॉक और रिपोर्ट।', 'Help is at the bottom of More.': 'मदद "और" में सबसे नीचे है।',
  // checklist
  'Getting started': 'शुरुआत', 'Make your first bill': 'अपना पहला बिल बनाएँ', 'Tap items, then Take payment.': 'आइटम टैप करें, फिर पेमेंट लें।', 'Scan a barcode': 'बारकोड स्कैन करें',
  'Point the camera at a product to add it.': 'जोड़ने के लिए कैमरा प्रोडक्ट की ओर करें।', 'Open a table': 'टेबल खोलें', 'Tap a free table to start an order.': 'ऑर्डर शुरू करने के लिए खाली टेबल पर टैप करें।',
  'See the kitchen screen': 'किचन स्क्रीन देखें', 'What the cooks see when you send an order.': 'ऑर्डर भेजने पर कुक क्या देखते हैं।', 'Hold a bill for later': 'बिल बाद के लिए होल्ड करें',
  'Put a bill aside when a customer steps away.': 'ग्राहक के हटने पर बिल अलग रख दें।', 'Look at your bills': 'अपने बिल देखें', 'Every bill you make is listed here.': 'आपके बनाए सारे बिल यहाँ दिखते हैं।',
  'Hide this. You can bring it back from Help.': 'इसे छिपाएँ। मदद से वापस ला सकते हैं।',
  // help guide
  'Make a bill': 'बिल बनाएँ', 'Keep billing when the internet is off': 'इंटरनेट बंद होने पर भी बिल बनाएँ', 'Change a price': 'कीमत बदलें', 'Fix a stock count': 'स्टॉक की गिनती ठीक करें',
  'Put a customer on a bill': 'बिल पर ग्राहक जोड़ें', 'Print a receipt': 'रसीद छापें', 'Take an order at a table': 'टेबल पर ऑर्डर लें', 'Use the kitchen screen': 'किचन स्क्रीन इस्तेमाल करें',
  'Open Sell.': 'बिक्री खोलें।', 'Tap the items on the menu. A drink with choices asks for size or milk first.': 'मेन्यू से आइटम टैप करें। विकल्प वाली ड्रिंक पहले साइज़ या दूध पूछती है।',
  'Tap an item, or scan its barcode with Scan.': 'आइटम टैप करें, या स्कैन से उसका बारकोड पढ़ें।', 'Check the bill with the Bill button. Use + and − to change a quantity.': 'बिल बटन से बिल जाँचें। मात्रा बदलने के लिए + और − दबाएँ।',
  'Tap Take payment, choose Cash, UPI or Card, then confirm.': 'पेमेंट लें दबाएँ, नकद, UPI या कार्ड चुनें, फिर पक्का करें।', 'Hand over the bill: Print or Share it, then tap New bill.': 'बिल दें: छापें या शेयर करें, फिर नया बिल दबाएँ।',
  'Just carry on. Make bills as usual.': 'बस जारी रखें। हमेशा की तरह बिल बनाएँ।', 'The line at the top says how many bills are waiting to send.': 'ऊपर की लाइन बताती है कि कितने बिल भेजने के इंतज़ार में हैं।',
  'When the signal is back they are sent by themselves, once each, in order.': 'इंटरनेट आने पर वे अपने आप, एक-एक बार, क्रम से भेज दिए जाते हैं।', 'A bill FlowXP cannot accept stays in Bills with the reason, for you to decide.': 'जो बिल FlowXP स्वीकार नहीं कर सकता वह कारण के साथ बिल में रहता है, आप फ़ैसला करें।',
  'On Sell, tap Hold and give it a name, like "Ravi" or "blue shirt".': 'बिक्री पर होल्ड दबाएँ और नाम दें, जैसे "रवि" या "नीली शर्ट"।', 'The till is clear for the next customer.': 'अगले ग्राहक के लिए बिल खाली है।', 'To carry on: More, then Bills on hold, then Resume.': 'आगे बढ़ने के लिए: और, फिर होल्ड पर बिल, फिर जारी रखें।',
  'Open Products and tap the item.': 'प्रोडक्ट खोलें और आइटम पर टैप करें।', 'Type the new price under Change the price.': 'कीमत बदलें के नीचे नई कीमत लिखें।', 'Tap Save price. New bills use it straight away.': 'कीमत सेव करें दबाएँ। नए बिल तुरंत इसे इस्तेमाल करते हैं।',
  'Open More, then Stock, and tap the item.': 'और खोलें, फिर स्टॉक, और आइटम पर टैप करें।', 'Type how many to add, or a minus number to take away.': 'कितने जोड़ने हैं लिखें, या घटाने के लिए माइनस नंबर लिखें।', 'Say why (counted, damaged, received) and tap Update stock.': 'कारण लिखें (गिनती, खराब, प्राप्त) और स्टॉक अपडेट करें दबाएँ।',
  'On Sell, tap Add customer.': 'बिक्री पर ग्राहक जोड़ें दबाएँ।', 'Search by name or phone, or tap Add customer for a new one.': 'नाम या फ़ोन से खोजें, या नए के लिए ग्राहक जोड़ें दबाएँ।', 'Their bill is saved under their name, and they earn their visit card stamp.': 'बिल उनके नाम से सेव होता है, और उन्हें विज़िट कार्ड की मुहर मिलती है।',
  'Open More, then Settings, and choose 58 mm or 80 mm paper.': 'और खोलें, फिर सेटिंग्स, और 58 mm या 80 mm कागज़ चुनें।', 'Tap Print a test receipt to check it lines up.': 'सही बैठ रहा है यह जाँचने के लिए टेस्ट रसीद छापें दबाएँ।', 'After any bill, tap Print.': 'किसी भी बिल के बाद छापें दबाएँ।',
  'Open Tables and tap a free table.': 'टेबल खोलें और खाली टेबल पर टैप करें।', 'Tap Add items, then tap what the guests want.': 'आइटम जोड़ें दबाएँ, फिर मेहमानों की पसंद पर टैप करें।', 'Tap Send to kitchen. The cooks see it at once.': 'किचन को भेजें दबाएँ। कुक उसे तुरंत देखते हैं।',
  'When the food is ready, tap Mark served.': 'खाना तैयार होने पर परोसा गया दबाएँ।', 'When the table is done, tap Bill and pay.': 'टेबल पूरी होने पर बिल और पेमेंट दबाएँ।',
  'Open More, then Kitchen screen. Leave it open: it stays awake and refreshes itself.': 'और खोलें, फिर किचन स्क्रीन। इसे खुला छोड़ दें: यह जागा रहता है और अपने आप रिफ़्रेश होता है।', 'Tap a dish when it is done, or All ready for the whole ticket.': 'डिश तैयार होने पर टैप करें, या पूरे टिकट के लिए सब तैयार दबाएँ।',
  'Rush puts a table first. Undo is on the bar for a few seconds.': 'जल्दी से टेबल सबसे पहले आती है। वापस का बटन कुछ सेकंड बार पर रहता है।', 'The phone buzzes for a new order, and for a dish that is late.': 'नए ऑर्डर और देर वाली डिश पर फ़ोन कंपन करता है।',
  // tables and bookings
  'Change the table': 'टेबल बदलें', 'Move': 'हटाएँ', 'Join': 'जोड़ें', 'Split': 'बाँटें', 'Waiter': 'वेटर', 'Table': 'टेबल', 'Bookings': 'बुकिंग',
  'Move this order to a free table': 'यह ऑर्डर खाली टेबल पर ले जाएँ', 'Move here': 'यहाँ ले जाएँ', 'No free table right now.': 'अभी कोई खाली टेबल नहीं है।',
  "Join another table's order into this one": 'दूसरी टेबल का ऑर्डर इसमें जोड़ें', 'Everything on that table comes here and ends up on one bill. That table becomes free.': 'उस टेबल का सब कुछ यहाँ आ जाता है और एक ही बिल बनता है। वह टेबल खाली हो जाती है।',
  'No other table has an order right now.': 'अभी किसी और टेबल पर ऑर्डर नहीं है।', 'Tap + on what moves, then choose where': 'जो हटाना है उस पर + दबाएँ, फिर जगह चुनें', 'Nothing on this order to move.': 'इस ऑर्डर में हटाने के लिए कुछ नहीं है।',
  'No other table to move them to.': 'उन्हें ले जाने के लिए कोई और टेबल नहीं है।', 'Only an order at a table can be moved, joined or split.': 'सिर्फ़ टेबल का ऑर्डर ही हटाया, जोड़ा या बाँटा जा सकता है।',
  'Who looks after this table': 'यह टेबल कौन देखता है', 'No waiters are set up for this outlet. Add them on the FlowXP website under Team.': 'इस आउटलेट के लिए कोई वेटर नहीं जोड़ा गया। FlowXP वेबसाइट पर टीम में जोड़ें।',
  'No one': 'कोई नहीं', 'Take the waiter off this table': 'इस टेबल से वेटर हटाएँ', 'Assign': 'सौंपें', 'Bookings and waiting': 'बुकिंग और इंतज़ार', 'Tables booked, guests waiting for one': 'बुक की गई टेबल, टेबल का इंतज़ार करते मेहमान',
  'Walk-in guests, in order': 'सीधे आए मेहमान, क्रम से', 'Waiting list': 'इंतज़ार सूची', 'Add a booking': 'बुकिंग जोड़ें', 'Add to waiting list': 'इंतज़ार सूची में जोड़ें',
  'In 30 min': '30 मिनट में', 'In 1 hour': '1 घंटे में', 'In 2 hours': '2 घंटे में', 'Table (optional)': 'टेबल (वैकल्पिक)', 'Decide later': 'बाद में तय करें',
  'Type the time like 19:30. Today only, and not already past.': 'समय ऐसे लिखें: 19:30। सिर्फ़ आज का, और बीता हुआ नहीं।', 'No bookings today. Tap Add a booking when a guest calls.': 'आज कोई बुकिंग नहीं। मेहमान का फ़ोन आए तो बुकिंग जोड़ें दबाएँ।',
  'They arrived': 'वे आ गए', 'Did not come': 'नहीं आए', 'Cancel booking': 'बुकिंग रद्द करें', 'Done today': 'आज पूरी हुईं', 'Seat': 'बैठाएँ', 'Table is ready': 'टेबल तैयार है', 'They left': 'वे चले गए',
  'Nobody is waiting. Add a walk-in guest when the tables are full.': 'कोई इंतज़ार में नहीं है। टेबल भरी हों तो सीधे आए मेहमान को जोड़ें।', 'Guest name': 'मेहमान का नाम', 'Mobile number (optional)': 'मोबाइल नंबर (वैकल्पिक)', 'How many people': 'कितने लोग', 'Time, like 19:30': 'समय, जैसे 19:30',
  'Booked': 'बुक', 'Seated': 'बैठे', 'Cancelled': 'रद्द',
  'Add to their order': 'उनके ऑर्डर में जोड़ें', 'Free table': 'खाली टेबल', 'Save': 'सेव करें',
  // returns, expenses, suppliers
  'Return items': 'सामान वापस लें', 'Choose what comes back': 'चुनें क्या वापस आ रहा है', 'Tap + on what is coming back': 'जो वापस आ रहा है उस पर + दबाएँ', 'Why': 'क्यों', 'Money': 'पैसा',
  'Wrong item': 'गलत आइटम', 'Damaged': 'खराब', 'Customer changed mind': 'ग्राहक ने मन बदला', 'Not as expected': 'उम्मीद के मुताबिक नहीं', 'Or type the reason': 'या कारण लिखें',
  'Cash back': 'नकद वापस', 'UPI back': 'UPI से वापस', 'Card back': 'कार्ड में वापस', 'No money back': 'पैसे वापस नहीं', 'Put the items back in stock': 'आइटम वापस स्टॉक में रखें', 'Confirm the return': 'वापसी पक्की करें',
  'This bill was cancelled, so nothing can be returned from it.': 'यह बिल रद्द हो चुका है, इसलिए इससे कुछ वापस नहीं हो सकता।', 'Everything on this bill has already been returned.': 'इस बिल का सब कुछ पहले ही वापस हो चुका है।',
  'Expenses': 'खर्चे', 'Rent, salary, electricity and the like': 'किराया, वेतन, बिजली वगैरह', 'Rent, salary, electricity: what you spent': 'किराया, वेतन, बिजली: आपने क्या खर्च किया', 'Spent': 'खर्च', 'Add an expense': 'खर्चा जोड़ें', 'What was it for?': 'यह किसलिए था?', 'Paid by': 'भुगतान किया',
  'Rent': 'किराया', 'Salary': 'वेतन', 'Electricity': 'बिजली', 'Supplies': 'सामान', 'Transport': 'ढुलाई', 'Repairs': 'मरम्मत', 'Other': 'अन्य', 'Cash': 'नकद', 'Bank': 'बैंक', 'Amount': 'रकम', 'A note (optional)': 'नोट (वैकल्पिक)',
  'No expenses in this time. Tap Add an expense when you pay for something.': 'इस समय में कोई खर्चा नहीं। कुछ चुकाएँ तो खर्चा जोड़ें दबाएँ।', 'Keep it': 'रहने दें', 'Remove': 'हटाएँ',
  'Suppliers': 'सप्लायर', 'Who you buy from': 'आप किससे खरीदते हैं', 'Suppliers and stock coming in': 'सप्लायर और आता हुआ स्टॉक', 'Who you buy from, and receive a delivery': 'आप किससे खरीदते हैं, और माल प्राप्त करें', 'Receive stock': 'माल प्राप्त करें', 'Add a supplier': 'सप्लायर जोड़ें', 'Supplier name': 'सप्लायर का नाम',
  'No suppliers yet. Add one, or receive stock without naming a supplier.': 'अभी कोई सप्लायर नहीं। एक जोड़ें, या बिना नाम बताए माल प्राप्त करें।', 'Paying a supplier is on the FlowXP website.': 'सप्लायर को भुगतान FlowXP वेबसाइट पर होता है।',
  'What came in today': 'आज क्या आया', 'From': 'किससे', 'No supplier': 'कोई सप्लायर नहीं', "Supplier's bill number (optional)": 'सप्लायर का बिल नंबर (वैकल्पिक)', 'Search an item to add': 'जोड़ने के लिए आइटम खोजें', 'Tap to add': 'जोड़ने के लिए टैप करें',
  'Search an item above and tap it to add it to this delivery.': 'ऊपर आइटम खोजें और इस माल में जोड़ने के लिए टैप करें।', 'How many': 'कितने', 'Cost each': 'हर एक की कीमत', 'Use-by date, like 2027-03-31 (if it expires)': 'इस्तेमाल की आखिरी तारीख, जैसे 2027-03-31 (अगर खराब होता है)', 'Paid now, in cash (optional)': 'अभी नकद चुकाया (वैकल्पिक)', 'Record the delivery': 'माल दर्ज करें',
  'Use-by dates': 'इस्तेमाल की तारीखें', 'Next 30 days and already past': 'अगले 30 दिन और बीत चुकी', 'What is expiring, and what has expired': 'क्या खत्म होने वाला है, और क्या खत्म हो चुका', 'Expiring soon': 'जल्द खत्म', 'Expired': 'खत्म हो चुका', 'Everything': 'सब कुछ',
  'Nothing here. Items with a use-by date appear when stock is received with one.': 'यहाँ कुछ नहीं। इस्तेमाल की तारीख वाले आइटम माल दर्ज करते समय तारीख देने पर दिखते हैं।', 'Tap an expired line to take it off the shelf.': 'खत्म हो चुकी लाइन पर टैप करके उसे शेल्फ से हटाएँ।', 'Write it off': 'बट्टे खाते में डालें',
  'Open Products': 'प्रोडक्ट खोलें', 'Open More': 'और खोलें',
  // salon
  'No client chosen': 'कोई क्लाइंट नहीं चुना', 'Appointments': 'अपॉइंटमेंट', 'Choose client': 'क्लाइंट चुनें', 'Change client': 'क्लाइंट बदलें', 'No client': 'कोई क्लाइंट नहीं', 'Services': 'सेवाएँ', 'Packages': 'पैकेज', 'Memberships': 'सदस्यता',
  'Search services': 'सेवाएँ खोजें', 'Search products or scan a barcode number': 'प्रोडक्ट खोजें या बारकोड नंबर लिखें', 'No service matches.': 'कोई सेवा नहीं मिली।', 'No product matches.': 'कोई प्रोडक्ट नहीं मिला।', 'This bill': 'यह बिल',
  'Tap a service to add it, then say who is doing it.': 'सेवा जोड़ने के लिए टैप करें, फिर बताएँ कौन कर रहा है।', 'Charge for it': 'इसका पैसा लें', 'How is the client paying?': 'क्लाइंट कैसे भुगतान कर रहा है?', 'On credit': 'उधार', 'Reference number (optional)': 'रेफरेंस नंबर (वैकल्पिक)',
  'Who is booked, who has arrived': 'कौन बुक है, कौन आ गया', 'Who is booked, and who has arrived': 'कौन बुक है, और कौन आ गया', 'Tomorrow': 'कल', 'Start the service': 'सेवा शुरू करें', 'Bill this visit': 'इस विज़िट का बिल बनाएँ',
  'No appointments for this day. A walk-in? Go to Sell and make a bill.': 'इस दिन कोई अपॉइंटमेंट नहीं। बिना बुकिंग आया? बिक्री पर जाकर बिल बनाएँ।', 'Billing is on the website for now': 'बिल अभी वेबसाइट पर बनते हैं',
  // salon: booking, gift cards, clients, team, reports
  'Add': 'जोड़ें', 'Add a note for the team': 'टीम के लिए नोट जोड़ें', 'Add the gift card': 'गिफ्ट कार्ड जोड़ें', 'Approve': 'मंज़ूर करें', 'Book': 'बुक करें', 'Check': 'जाँचें', 'Clients': 'क्लाइंट',
  'Gift card code (optional)': 'गिफ्ट कार्ड कोड (वैकल्पिक)', 'New': 'नया', 'New guest name': 'नए मेहमान का नाम', 'Offer code (optional)': 'ऑफ़र कोड (वैकल्पिक)', 'Or type an amount': 'या रकम लिखें',
  'Pay in cash': 'नकद चुकाएँ', 'Points': 'पॉइंट', 'Points to spend (optional)': 'खर्च करने के पॉइंट (वैकल्पिक)', 'Salon reports': 'सैलून रिपोर्ट', 'Save note': 'नोट सेव करें', 'Team': 'टीम',
  'Today at a glance, and every report': 'आज एक नज़र में, और हर रिपोर्ट', 'Visits, memberships, notes and history': 'विज़िट, सदस्यता, नोट और इतिहास', 'Who is in today, and commission': 'आज कौन आया है, और कमीशन',
  'Book an appointment': 'अपॉइंटमेंट बुक करें', 'Move appointment': 'अपॉइंटमेंट बदलें', 'Gift cards': 'गिफ्ट कार्ड', 'Move it': 'बदलें', 'Book it': 'बुक करें', 'Day': 'दिन', 'Time': 'समय', 'Client': 'क्लाइंट', 
  'Choose an existing client': 'पुराना क्लाइंट चुनें', 'Anyone free': 'जो भी खाली हो', 'Team member': 'टीम सदस्य', 'Choose a service to see free times.': 'खाली समय देखने के लिए सेवा चुनें।',
  'Nobody is free on this day for these services. Try another day or team member.': 'इस दिन इन सेवाओं के लिए कोई खाली नहीं। दूसरा दिन या टीम सदस्य आज़माएँ।', 'What they have': 'उनके पास क्या है', 'Notes': 'नोट', 'History': 'इतिहास',
  'Sell a gift card. Its value goes to the client on this bill when it is paid.': 'गिफ्ट कार्ड बेचें। भुगतान होने पर उसकी रकम इस बिल के क्लाइंट को मिलती है।', 'Commission': 'कमीशन', 'To approve': 'मंज़ूरी बाकी', 'To pay': 'चुकाना बाकी', 'Paid': 'चुकाया',
  'Today and every report': 'आज और हर रिपोर्ट', 'This month': 'इस महीने', 'Total': 'कुल',
  // pharmacy
  'A delivery from a supplier, batch by batch': 'सप्लायर से माल, बैच के हिसाब से', 'Batch number': 'बैच नंबर', 'Batches and use-by dates': 'बैच और इस्तेमाल की तारीख', 'Cost of one (what you pay)': 'एक की कीमत (जो आप चुकाते हैं)',
  "Doctor's name (optional)": 'डॉक्टर का नाम (वैकल्पिक)', 'How many came': 'कितने आए', 'Made on, like 03/2025 (optional)': 'बनने की तारीख, जैसे 03/2025 (वैकल्पिक)', 'Medicine name, salt or barcode': 'दवा का नाम, सॉल्ट या बारकोड',
  'No customer': 'कोई ग्राहक नहीं', "Patient's name (optional)": 'मरीज़ का नाम (वैकल्पिक)', 'Receive medicines': 'दवाएँ प्राप्त करें', 'Search a medicine to add': 'जोड़ने के लिए दवा खोजें',
  "Supplier's invoice number (optional)": 'सप्लायर का बिल नंबर (वैकल्पिक)', 'Use by, like 03/2027': 'इस्तेमाल की आखिरी तारीख, जैसे 03/2027', 'What is expiring, hold back or recall a batch': 'क्या खत्म होने वाला है, बैच रोकें या वापस बुलाएँ',
  'Search a medicine above, or tap Scan, and tap it to add it.': 'ऊपर दवा खोजें या स्कैन दबाएँ, और जोड़ने के लिए उस पर टैप करें।', 'Prescription medicine': 'पर्चे वाली दवा', 'I have checked the prescription': 'मैंने पर्चा देख लिया है',
  'How is the customer paying?': 'ग्राहक कैसे भुगतान कर रहा है?', 'No medicine matches.': 'कोई दवा नहीं मिली।', 'Choose batch': 'बैच चुनें', 'Automatic batch': 'अपने आप बैच', 'Hold back': 'रोकें', 'Recall': 'वापस बुलाएँ', 'Block': 'ब्लॉक करें', 'Put back on sale': 'फिर से बिक्री पर रखें',
  'Held back': 'रोका हुआ', 'On sale': 'बिक्री पर', 'Recalled': 'वापस बुलाया', 'Blocked': 'ब्लॉक',
  // wholesale
  'Orders and payments': 'ऑर्डर और भुगतान', 'Take an order for a customer, or collect what they owe': 'ग्राहक का ऑर्डर लें, या उनसे बकाया वसूलें', 'New order': 'नया ऑर्डर', 'Collect payment': 'भुगतान वसूलें', 'Orders': 'ऑर्डर',
  'Customer accounts': 'ग्राहक खाते', 'Who owes what, and their credit': 'किस पर कितना बकाया, और उनकी उधारी', 'What customers have ordered': 'ग्राहकों ने क्या ऑर्डर किया', 'A customer pays what they owe': 'ग्राहक अपना बकाया चुकाता है',
  'Who buys, and who owes': 'कौन खरीदता है, और किस पर बकाया है', 'Search by name, phone or GST number': 'नाम, फ़ोन या GST नंबर से खोजें', 'Everyone': 'सब', 'Owe money': 'बकाया वाले', 'Overdue': 'देर से',
  'Order number, customer or their PO': 'ऑर्डर नंबर, ग्राहक या उनका PO', 'Open': 'खुले', 'Waiting for approval': 'मंज़ूरी का इंतज़ार', 'Finished': 'पूरे हुए', 'No orders here. Tap New to take one.': 'यहाँ कोई ऑर्डर नहीं। लेने के लिए नया दबाएँ।',
  'Search a product by name, code or barcode': 'नाम, कोड या बारकोड से प्रोडक्ट खोजें', 'Search a product above and tap it to add it.': 'ऊपर प्रोडक्ट खोजें और जोड़ने के लिए उस पर टैप करें।', 'Customer\'s PO number (optional)': 'ग्राहक का PO नंबर (वैकल्पिक)',
  'Wanted by, like 2026-10-20 (optional)': 'कब तक चाहिए, जैसे 2026-10-20 (वैकल्पिक)', 'Submit the order': 'ऑर्डर भेजें', 'Save as draft': 'ड्राफ़्ट सेव करें', 'Choose customer': 'ग्राहक चुनें', 'Change customer': 'ग्राहक बदलें',
  'Amount received': 'मिली रकम', 'How was it paid?': 'भुगतान कैसे हुआ?', 'Put it against': 'किस बिल में लगाएँ', 'Oldest bills first': 'सबसे पुराने बिल पहले', 'This will settle': 'इससे ये चुकेंगे', 'Record the payment': 'भुगतान दर्ज करें',
  'Cheque number': 'चेक नंबर', 'Transaction reference': 'लेन-देन रेफरेंस', 'Cheque date, like 2026-10-20 (optional)': 'चेक की तारीख, जैसे 2026-10-20 (वैकल्पिक)', 'Bank (optional)': 'बैंक (वैकल्पिक)', 'Bank transfer': 'बैंक ट्रांसफ़र', 'Cheque': 'चेक',
  'Bills not yet paid': 'बिना चुकाए बिल', 'Latest orders': 'ताज़ा ऑर्डर', 'Account statement': 'खाता विवरण', 'Sent out': 'भेजा गया', 'Send for approval': 'मंज़ूरी के लिए भेजें', 'Confirm': 'पक्का करें', 'Cancel order': 'ऑर्डर रद्द करें',
  'Confirm anyway (manager)': 'फिर भी पक्का करें (मैनेजर)', 'Owed to you': 'आपको बकाया', 'Collected today': 'आज वसूला', 'Billed today': 'आज बिल बने', 'Billed this month': 'इस महीने बिल बने', 'Who owes the most': 'सबसे ज़्यादा बकाया किसका',
  // field sales
  'My route': 'मेरा रूट', "Today's shops, in order": 'आज की दुकानें, क्रम से', "Today's shops, orders and payments in the field": 'आज की दुकानें, फ़ील्ड में ऑर्डर और भुगतान', 'Visited': 'मिल चुके', 'Orders today': 'आज के ऑर्डर', 'Month target': 'महीने का लक्ष्य',
  'No shops on your beat today. Beats are planned on the FlowXP website.': 'आज आपके रूट पर कोई दुकान नहीं। रूट FlowXP वेबसाइट पर तय होते हैं।', 'Take an order': 'ऑर्डर लें', 'Not buying today?': 'आज नहीं खरीद रहे?',
  'Took an order': 'ऑर्डर लिया', 'Collected a payment': 'भुगतान वसूला', 'No order today': 'आज ऑर्डर नहीं', 'Shop was closed': 'दुकान बंद थी', 'Owner not there': 'मालिक नहीं थे', 'Come back later': 'बाद में आना है',
  'Come back on, like 2026-10-15': 'कब आना है, जैसे 2026-10-15', 'Record the visit': 'विज़िट दर्ज करें', 'Last orders': 'पिछले ऑर्डर', 'Last visits': 'पिछली विज़िट', "Shop's PO number (optional)": 'दुकान का PO नंबर (वैकल्पिक)', 'Send the order': 'ऑर्डर भेजें', 'Back to my route': 'मेरे रूट पर वापस',
  // van sales
  'My van': 'मेरी गाड़ी', 'What you are carrying': 'आप क्या लेकर चल रहे हैं', 'What you carry, and sell from it': 'आप क्या ले जाते हैं, और उससे बेचें', 'Sell from the van': 'गाड़ी से बेचें', 'Sold today': 'आज बिका', 'Products on the van': 'गाड़ी में प्रोडक्ट', 'On the van': 'गाड़ी में',
  'The van is empty. Stock is loaded at the warehouse.': 'गाड़ी खाली है। माल गोदाम में लादा जाता है।', 'No van is assigned to you. Vans are set up on the FlowXP website.': 'आपको कोई गाड़ी नहीं दी गई। गाड़ियाँ FlowXP वेबसाइट पर तय होती हैं।',
  'Loading the van, taking unsold stock back and the end-of-day count are done by the warehouse on the FlowXP website.': 'गाड़ी में माल लादना, बिना बिका माल वापस लेना और दिन के अंत की गिनती गोदाम FlowXP वेबसाइट पर करता है।',
  'Choose the shop': 'दुकान चुनें', 'Change shop': 'दुकान बदलें', 'Search what the van carries': 'गाड़ी में क्या है, खोजें', 'This sale': 'यह बिक्री', 'Tap a product above to add it.': 'ऊपर प्रोडक्ट पर टैप करके जोड़ें।', 'How is it paid?': 'भुगतान कैसे हुआ?',
  'Paid in full': 'पूरा चुकाया', 'Part paid': 'कुछ चुकाया', 'How much was paid': 'कितना चुकाया', 'Make the sale': 'बिक्री करें', 'Back to my van': 'मेरी गाड़ी पर वापस',
  'Reference number': 'रेफरेंस नंबर',
  // warehouse
  'Warehouse': 'गोदाम', 'Pick, pack and send out': 'निकालें, पैक करें और भेजें', 'Pick, pack and send out orders': 'ऑर्डर निकालें, पैक करें और भेजें', 'To pick': 'निकालने हैं', 'Pick lists': 'पिक लिस्ट', 'On the road': 'रास्ते में',
  'Orders to pick': 'निकालने वाले ऑर्डर', 'Being picked': 'निकाले जा रहे', 'Ready to pack': 'पैक के लिए तैयार', 'Ready to send out': 'भेजने के लिए तैयार', 'Could not deliver': 'पहुँचा नहीं सके',
  'No confirmed order is waiting to be picked.': 'कोई पक्का ऑर्डर निकालने के लिए इंतज़ार में नहीं है।', 'No pick lists in hand. Start one from an order under To pick.': 'कोई पिक लिस्ट नहीं। निकालने हैं में किसी ऑर्डर से शुरू करें।', 'Nothing is on the road.': 'रास्ते में कुछ नहीं है।',
  'Scan an item': 'आइटम स्कैन करें', 'Tick': 'निशान लगाएँ', 'Start picking': 'निकालना शुरू करें', 'Pack it': 'पैक करें', 'Weight in kg (optional)': 'वज़न किलो में (वैकल्पिक)', 'Send it out': 'भेज दें',
  'Vehicle number (optional)': 'गाड़ी नंबर (वैकल्पिक)', "Driver's name (optional)": 'ड्राइवर का नाम (वैकल्पिक)', "Driver's mobile number (optional)": 'ड्राइवर का मोबाइल नंबर (वैकल्पिक)', 'The bill': 'बिल', 'Tax invoice': 'टैक्स इनवॉइस', 'Paid now': 'अभी चुकाया',
  'Payment reference': 'भुगतान रेफरेंस', 'Cancel pick list': 'पिक लिस्ट रद्द करें', 'Everything picked goes in one package. More boxes are set up on the FlowXP website.': 'जो निकाला वह एक पैकेज में जाता है। ज़्यादा डिब्बे FlowXP वेबसाइट पर बनते हैं।',
  'What happened?': 'क्या हुआ?', 'Who received it?': 'किसने लिया?', 'Why? (a few words)': 'क्यों? (कुछ शब्द)', 'Out for delivery': 'डिलीवरी के लिए निकला', 'Delivered': 'पहुँच गया', 
  'Came back to the warehouse': 'गोदाम वापस आया', 'Open the bill': 'बिल खोलें',
  // buying
  'Buying': 'खरीद', 'Orders to suppliers, and goods coming in': 'सप्लायर को ऑर्डर, और आता हुआ माल', 'Receive without an order': 'बिना ऑर्डर के माल लें', 'Due in': 'आने वाला', 'Drafts': 'ड्राफ़्ट', 'Ordered': 'ऑर्डर दिया', 'Owed to suppliers': 'सप्लायर को बकाया', 
  'Order number or supplier': 'ऑर्डर नंबर या सप्लायर', 'Nothing is due to arrive. Orders that are approved and not yet delivered show here.': 'कुछ आने वाला नहीं। मंज़ूर हुए और अभी न पहुँचे ऑर्डर यहाँ दिखते हैं।', 'No orders here.': 'यहाँ कोई ऑर्डर नहीं।',
  'New order to a supplier': 'सप्लायर को नया ऑर्डर', 'It is saved as a draft until it is approved': 'मंज़ूरी तक यह ड्राफ़्ट रहता है', 'Search a product to order': 'ऑर्डर के लिए प्रोडक्ट खोजें', 'Cost of one (blank: the supplier\'s price list)': 'एक की कीमत (खाली: सप्लायर की रेट लिस्ट)',
  'Expected by, like 2026-10-20 (optional)': 'कब तक चाहिए, जैसे 2026-10-20 (वैकल्पिक)', "A note for the supplier (optional)": 'सप्लायर के लिए नोट (वैकल्पिक)', 'Save the order': 'ऑर्डर सेव करें', 'Approve and order': 'मंज़ूर करें और ऑर्डर दें', 'Send to the supplier': 'सप्लायर को भेजें',
  'Receive goods': 'माल प्राप्त करें', 'Receive more goods': 'और माल प्राप्त करें', 'Close: no more is coming': 'बंद करें: और कुछ नहीं आएगा', 'Pay the supplier': 'सप्लायर को चुकाएँ', 'Amount paid': 'चुकाई रकम', 'Goods received': 'प्राप्त माल', 
  'Accept more than was ordered': 'ऑर्डर से ज़्यादा भी स्वीकार करें', 'Close the order: no more is coming': 'ऑर्डर बंद करें: और कुछ नहीं आएगा', 
  "Supplier's bill date, like 2026-10-08 (optional)": 'सप्लायर के बिल की तारीख, जैसे 2026-10-08 (वैकल्पिक)', 'Cost of one, if different from the order (optional)': 'एक की कीमत, अगर ऑर्डर से अलग हो (वैकल्पिक)',
  'Paid now (optional)': 'अभी चुकाया (वैकल्पिक)', 'Search a product to add': 'जोड़ने के लिए प्रोडक्ट खोजें',
  // returns
  'Returns': 'वापसी', 'Goods that came back, and goods sent back': 'लौटा माल, और वापस भेजा माल', 'Goods a shop sent back, and goods sent back to a supplier': 'दुकान का लौटाया माल, और सप्लायर को वापस भेजा माल', 'A shop returns goods': 'दुकान माल लौटाती है', 'Send back to a supplier': 'सप्लायर को वापस भेजें',
  'From shops': 'दुकानों से', 'To suppliers': 'सप्लायरों को', 'No returns here yet.': 'यहाँ अभी कोई वापसी नहीं।', 'They are returning goods': 'वे माल लौटा रहे हैं', 'Which bill?': 'कौन सा बिल?', 'This shop has no bills yet.': 'इस दुकान का अभी कोई बिल नहीं।',
  'Why is it coming back?': 'यह वापस क्यों आ रहा है?', 'How many of each?': 'हर एक कितना?', 'Where do the goods go?': 'माल कहाँ जाएगा?', 'If they have already paid': 'अगर उन्होंने पहले ही चुका दिया हो', 
  'Back on the shelf': 'वापस शेल्फ पर', 'Damaged: not for sale': 'खराब: बिक्री के लिए नहीं', 'Not coming back to us': 'हमारे पास वापस नहीं आ रहा',
  'No money back: take it off what they owe': 'पैसे वापस नहीं: उनके बकाया से घटाएँ', 
  'Why are they going back?': 'ये वापस क्यों जा रहे हैं?', 'How many of each go back?': 'हर एक कितना वापस जाएगा?',
  'Choose the order the goods came on': 'वह ऑर्डर चुनें जिस पर माल आया था', 'No order has had goods delivered yet.': 'किसी ऑर्डर पर अभी माल नहीं आया।', 'Nothing has arrived on this order, so nothing can go back.': 'इस ऑर्डर पर कुछ नहीं आया, इसलिए कुछ वापस नहीं जा सकता।',
  'The oldest stock goes back first. Stock that is promised to customers cannot be sent back.': 'सबसे पुराना माल पहले वापस जाता है। ग्राहकों के लिए रखा माल वापस नहीं भेजा जा सकता।', 'Confirm: send it back': 'पक्का करें: वापस भेजें',
  'Goods a shop sent back': 'दुकान का लौटाया माल', 'Goods sent back to a supplier': 'सप्लायर को वापस भेजा माल',
  'Go to Sell': 'बिक्री पर जाएँ', 'See held bills': 'होल्ड बिल देखें', 'Go to Products': 'प्रोडक्ट पर जाएँ', 'Go to Stock': 'स्टॉक पर जाएँ', 'Go to Customers': 'ग्राहक पर जाएँ', 'Printer settings': 'प्रिंटर सेटिंग्स', 'Go to Tables': 'टेबल पर जाएँ', 'Open the kitchen screen': 'किचन स्क्रीन खोलें', 'Try it now': 'अभी आज़माएँ',
  'Price lists': 'प्राइस लिस्ट', 'Price list': 'प्राइस लिस्ट', 'Who pays what': 'कौन कितना देता है', 'Who pays what, and offer prices': 'कौन कितना देता है, और ऑफ़र के दाम', 'New list': 'नई लिस्ट', 'Make the list': 'लिस्ट बनाएँ', 'Name, for example Dealers': 'नाम, जैसे डीलर', 'Give the list a name': 'लिस्ट को नाम दें', 'Everyday prices': 'रोज़ के दाम', 'Offer prices': 'ऑफ़र के दाम', 'Could not make the list': 'लिस्ट नहीं बन सकी', 'No price list yet. Everyone pays the shelf wholesale price.': 'अभी कोई प्राइस लिस्ट नहीं। सब शेल्फ का थोक दाम देते हैं।', 'Switch off': 'बंद करें', 'Switch on': 'चालू करें', 'Use for everyone': 'सबके लिए रखें', 'Not for everyone': 'सबके लिए नहीं', 'Save the dates': 'तारीखें सहेजें', 'From (2026-11-01)': 'से (2026-11-01)', 'Until (2026-11-30)': 'तक (2026-11-30)', 'Add or change a price': 'दाम जोड़ें या बदलें', 'Search for an item': 'आइटम खोजें', 'Sold by': 'इस इकाई में बिकता है', 'A fixed price': 'तय दाम', 'A percentage off': 'प्रतिशत छूट', 'Price of one': 'एक का दाम', 'Percent off': 'कितने प्रतिशत छूट', 'They get this price when they buy at least': 'कम से कम इतना लेने पर यह दाम मिलेगा', 'Save this price': 'यह दाम सहेजें', 'Prices on this list': 'इस लिस्ट के दाम', 'No price yet. Customers on this list pay the normal price.': 'अभी कोई दाम नहीं। इस लिस्ट के ग्राहक सामान्य दाम देते हैं।', 'Keep': 'रखें', 'The customers on this list pay the normal price for it again.': 'इस लिस्ट के ग्राहक इसके लिए फिर सामान्य दाम देंगे।', 'That did not save': 'सहेजा नहीं जा सका', 'Choose an item first': 'पहले आइटम चुनें', 'Enter the price': 'दाम लिखें', 'Enter how much off': 'छूट कितनी है, लिखें', 'The discount cannot be more than 100%': 'छूट 100% से ज़्यादा नहीं हो सकती', 'Enter how many they must buy for this price': 'इस दाम के लिए कम से कम कितना लेना होगा, लिखें', 'Change price list': 'प्राइस लिस्ट बदलें', 'Close': 'बंद करें', 'None': 'कोई नहीं', 'Could not change the price list': 'प्राइस लिस्ट नहीं बदली जा सकी',
  'Moving stock': 'स्टॉक भेजना', 'Between your warehouses': 'आपके गोदामों के बीच', 'Send goods between warehouses, and receive them': 'गोदामों के बीच माल भेजें और पाएँ', 'Not finished': 'अधूरे', 'Not sent yet': 'अभी भेजा नहीं', 'On the way': 'रास्ते में', 'Received': 'मिल गया', 'Nothing is being moved right now.': 'अभी कुछ नहीं भेजा जा रहा।', 'Nothing here.': 'यहाँ कुछ नहीं।', 'Move stock': 'स्टॉक भेजें', 'From one warehouse to another': 'एक गोदाम से दूसरे गोदाम में', 'Goods leave from': 'माल यहाँ से जाएगा', 'and go to': 'और यहाँ पहुँचेगा', 'You have only one warehouse. Add another on the website to move stock between them.': 'आपके पास एक ही गोदाम है। स्टॉक भेजने के लिए वेबसाइट पर दूसरा जोड़ें।', 'What is going': 'क्या जा रहा है', 'Send it now': 'अभी भेजें', 'Keep it, send later': 'रख लें, बाद में भेजें', 'Sending takes the goods off the first warehouse. They are added to the other one when it marks them as received.': 'भेजते ही माल पहले गोदाम से कम हो जाता है। दूसरा गोदाम "मिल गया" दबाए तब वहाँ जुड़ता है।', 'Could not save the transfer': 'ट्रांसफर सहेजा नहीं जा सका', 'Choose the warehouse the goods leave from': 'वह गोदाम चुनें जहाँ से माल जाएगा', 'Choose the warehouse they go to': 'वह गोदाम चुनें जहाँ माल जाएगा', 'Choose two different warehouses': 'दो अलग गोदाम चुनें', 'Add the items and how many': 'आइटम और कितने, जोड़ें', 'Each quantity must be more than zero': 'हर मात्रा शून्य से ज़्यादा होनी चाहिए', 'Mark as received': 'मिल गया दर्ज करें', 'Drop it': 'हटा दें', 'Cancel: goods go back': 'रद्द करें: माल वापस जाएगा', 'Cancel this transfer?': 'यह ट्रांसफर रद्द करें?', 'Drop this transfer?': 'यह ट्रांसफर हटाएँ?', 'The goods go back into the warehouse they left.': 'माल उसी गोदाम में वापस चला जाएगा जहाँ से गया था।', 'Nothing has left the warehouse yet.': 'अभी गोदाम से कुछ नहीं निकला है।', 'Yes, cancel': 'हाँ, रद्द करें', 'That did not work': 'यह नहीं हो सका', 'What arrived?': 'क्या पहुँचा?', 'Everything is filled in as arrived in good condition. Change only what is different.': 'सब कुछ ठीक हालत में पहुँचा मानकर भरा है। जो अलग है, सिर्फ़ वही बदलें।', 'Good': 'ठीक', 'Confirm: it has arrived': 'पक्का करें: माल पहुँच गया', 'Everything arrived in good condition.': 'सब कुछ ठीक हालत में पहुँचा।',
  'Add medicine': 'दवा जोड़ें', 'New medicine': 'नई दवा', 'Medicine': 'दवा', 'Edit medicine details': 'दवा की जानकारी बदलें', 'Medicine added': 'दवा जुड़ गई', 'For example Paracetamol 500': 'जैसे पैरासिटामोल 500', 'Strength': 'ताकत', 'For example 500 mg': 'जैसे 500 mg', 'Form': 'रूप', 'Salt or composition': 'सॉल्ट या संघटन', 'For example Paracetamol': 'जैसे पैरासिटामोल', 'Made by': 'निर्माता', 'Price': 'दाम', 'MRP': 'एमआरपी', 'Printed on the pack': 'पैक पर छपा', 'What you pay (optional)': 'आप कितने में लेते हैं (वैकल्पिक)', 'strip, bottle, piece': 'पत्ता, बोतल, पीस', 'Rules': 'नियम', 'Schedule': 'शेड्यूल', 'Not scheduled': 'शेड्यूल नहीं', 'Schedule H': 'शेड्यूल H', 'Schedule H1': 'शेड्यूल H1', 'Schedule X': 'शेड्यूल X', 'Needs a prescription': 'पर्चा ज़रूरी', 'Scheduled medicines always need one.': 'शेड्यूल वाली दवा के लिए पर्चा हमेशा ज़रूरी है।', 'Keep a use-by date for each batch': 'हर बैच की एक्सपायरी तारीख रखें', 'Cannot be switched off while there is stock.': 'स्टॉक रहते इसे बंद नहीं कर सकते।', 'Strongly advised for medicines.': 'दवाओं के लिए ज़रूर रखें।', 'Track by batch': 'बैच के हिसाब से रखें', 'HSN code': 'एचएसएन कोड', 'Tell me when stock falls to': 'स्टॉक इतना रह जाए तो बताएँ', 'Reorder level (optional)': 'दोबारा मँगाने का स्तर (वैकल्पिक)', 'Add the medicine': 'दवा जोड़ें', 'Save the changes': 'बदलाव सहेजें', 'Remove this medicine': 'यह दवा हटाएँ', 'Remove this medicine?': 'यह दवा हटाएँ?', 'Could not remove it': 'हटा नहीं सके', 'Could not save the medicine': 'दवा सहेजी नहीं जा सकी', 'It has no stock yet.': 'अभी इसका स्टॉक नहीं है।', 'Add its stock with Receive medicines, so each batch has its use-by date.': 'इसका स्टॉक "दवाएँ प्राप्त करें" से जोड़ें, ताकि हर बैच की तारीख रहे।', 'Receive stock now': 'स्टॉक अभी जोड़ें', 'Tablet': 'टैबलेट', 'Capsule': 'कैप्सूल', 'Syrup': 'सिरप', 'Injection': 'इंजेक्शन', 'Ointment': 'मरहम', 'Drops': 'ड्रॉप्स', 'Powder': 'पाउडर', 'Give the medicine a name': 'दवा का नाम लिखें', 'Enter the selling price': 'बिक्री का दाम लिखें', 'Enter the MRP as a number': 'एमआरपी संख्या में लिखें', 'The selling price cannot be more than the MRP': 'बिक्री का दाम एमआरपी से ज़्यादा नहीं हो सकता', 'Enter the cost as a number': 'खरीद का दाम संख्या में लिखें', 'Enter the reorder level as a number': 'दोबारा मँगाने का स्तर संख्या में लिखें', 'Say how it is sold (strip, bottle, piece)': 'बताएँ किस इकाई में बिकती है (पत्ता, बोतल, पीस)',
  'Finish setting up FlowXP': 'FlowXP की सेटिंग पूरी करें', 'Show all steps': 'सारे कदम देखें', 'Show less': 'कम दिखाएँ', "Today's business": 'आज का कारोबार', 'Add expense': 'खर्च जोड़ें', 'See what to order': 'देखें क्या मँगाना है', 'Stock and buying': 'स्टॉक और खरीद', 'Your business': 'आपका कारोबार',
  'Popular': 'ज़्यादा बिकने वाले', 'Exact': 'ठीक इतना', 'Payment received': 'भुगतान मिल गया', 'Send the bill': 'बिल भेजें',
  'Large text': 'बड़े अक्षर', 'Normal text': 'सामान्य अक्षर',
  'Order more': 'और मँगाएँ', 'More about this item': 'इस आइटम के बारे में और', 'Why? (or choose above)': 'क्यों? (या ऊपर से चुनें)', 'Out of stock': 'स्टॉक खत्म', 'Low stock': 'स्टॉक कम', 'In stock': 'स्टॉक में', 'Everything is in stock': 'सब कुछ स्टॉक में है', 'Add stock': 'स्टॉक जोड़ें', 'Adjust stock': 'स्टॉक ठीक करें', 'How many came in?': 'कितने आए?', 'Add to stock': 'स्टॉक में जोड़ें', 'Save the change': 'बदलाव सहेजें', 'Counted': 'गिनती की', 'Used in the kitchen': 'किचन में इस्तेमाल हुआ', 'Gift or sample': 'गिफ़्ट या सैंपल', 'Enter how many came in': 'कितने आए, लिखें', 'To take stock away, use Adjust stock': 'स्टॉक घटाने के लिए "स्टॉक ठीक करें" इस्तेमाल करें', 'Enter how many to add (like 10) or take away (like -3)': 'कितने जोड़ने हैं (जैसे 10) या घटाने हैं (जैसे -3), लिखें', 'Say why you are changing the stock': 'बताएँ स्टॉक क्यों बदल रहे हैं', 'Could not change the stock': 'स्टॉक बदला नहीं जा सका', 'Stock received': 'स्टॉक मिला', 'No stock is being counted yet. Turn on "Count the stock" for an item to see it here.': 'अभी किसी का स्टॉक नहीं गिना जा रहा। किसी आइटम पर "स्टॉक गिनें" चालू करें, तब वह यहाँ दिखेगा।',
  'How much did they pay?': 'उन्होंने कितना दिया?', 'Money received': 'पैसे मिल गए', 'Reference (optional)': 'रेफ़रेंस (वैकल्पिक)', 'Customer dues': 'ग्राहकों का बकाया', 'Best customers': 'सबसे अच्छे ग्राहक', 'Nobody owes you anything.': 'किसी का कुछ बकाया नहीं।', 'No purchases yet.': 'अभी कोई खरीद नहीं।', 'No customers yet. Add a customer to keep their bills and what they owe.': 'अभी कोई ग्राहक नहीं। ग्राहक जोड़ें ताकि उनके बिल और बकाया रहें।', 'Enter how much they paid': 'उन्होंने कितना दिया, लिखें', 'That is more than they owe on this bill': 'यह इस बिल के बकाया से ज़्यादा है', 'The payment did not go through. Your data is safe. Try again.': 'भुगतान दर्ज नहीं हुआ। आपका डेटा सुरक्षित है। फिर कोशिश करें।', 'UPI': 'UPI', 'Card': 'कार्ड',
  'Estimated profit': 'अनुमानित मुनाफ़ा', 'Still owed to you': 'आपको अभी भी मिलना है', 'What happened': 'क्या हुआ', 'No sales in this period yet. Make a bill and it shows up here.': 'इस अवधि में अभी कोई बिक्री नहीं। बिल बनाएँ, यहाँ दिखेगा।', 'View detailed reports': 'पूरी रिपोर्ट देखें', 'Hide detailed reports': 'पूरी रिपोर्ट छिपाएँ',
  'Ask Flow AI': 'Flow AI से पूछें', 'Questions about your business, in plain words': 'अपने कारोबार के बारे में सवाल, आसान शब्दों में', 'Earlier': 'पहले के', 'Start a new chat': 'नई बातचीत शुरू करें', 'Earlier chats': 'पहले की बातचीत', 'Nothing here yet. Ask your first question.': 'अभी कुछ नहीं। अपना पहला सवाल पूछें।', 'What would you like to know?': 'आप क्या जानना चाहते हैं?', 'Give me my daily briefing': 'मुझे आज का सार दें', 'Looking at your records…': 'आपके रिकॉर्ड देख रहा हूँ…', 'Ask a question': 'सवाल पूछें', 'Send': 'भेजें', 'Ask Flow AI about this': 'इस बारे में Flow AI से पूछें', 'Flow AI is not set up yet': 'Flow AI अभी चालू नहीं है', 'Flow AI is switched off': 'Flow AI बंद है', 'No questions left this month': 'इस महीने के सवाल खत्म', 'Keep the question a little shorter': 'सवाल थोड़ा छोटा रखें', 'Flow AI is not set up yet. Everything else in the app works as usual.': 'Flow AI अभी चालू नहीं है। ऐप में बाकी सब पहले जैसा चलता है।', 'Flow AI is switched off for this business.': 'इस कारोबार के लिए Flow AI बंद है।', 'You have used all your questions this month. They come back next month.': 'इस महीने के सारे सवाल हो गए। अगले महीने फिर मिलेंगे।', 'That was a lot of questions at once. Wait a minute and try again.': 'एक साथ बहुत सवाल हो गए। एक मिनट रुककर फिर कोशिश करें।', 'Flow AI is for owners and managers.': 'Flow AI मालिकों और मैनेजरों के लिए है।', 'Could not connect. Your questions need the internet. Try again when you are online.': 'जुड़ नहीं सके। सवालों के लिए इंटरनेट चाहिए। इंटरनेट आने पर फिर कोशिश करें।', 'Flow AI could not answer just now. Please try again.': 'Flow AI अभी जवाब नहीं दे सका। कृपया फिर कोशिश करें।', 'How much did I sell today?': 'आज मैंने कितना बेचा?', 'Which item sells the most?': 'कौन सा आइटम सबसे ज़्यादा बिकता है?', 'Why are my sales lower this week?': 'इस हफ़्ते बिक्री कम क्यों है?', 'How much food did I waste?': 'कितना खाना बर्बाद हुआ?',
  'Something changed on another device': 'किसी दूसरे डिवाइस पर कुछ बदल गया', 'Choose which to keep': 'चुनें कौन सा रखना है', 'Changed on another device: you decide': 'दूसरे डिवाइस पर बदला: आप तय करें',
  '{label}. FlowXP now has {price}. Which one should we keep?': '{label}। FlowXP में अभी {price} है। कौन सा रखें?', 'Keep my change ({price})': 'मेरा बदलाव रखें ({price})', "Keep FlowXP's ({price})": 'FlowXP वाला रखें ({price})',
  'Loading the bill': 'बिल लोड हो रहा है', 'GST': 'जीएसटी',
  'Service menu': 'सर्विस मेन्यू', 'What you offer, its price and how long it takes': 'आप क्या देते हैं, उसका दाम और कितना समय लगता है', 'What you offer, and what it costs': 'आप क्या देते हैं, और उसका दाम', 'Search for a service': 'सर्विस खोजें', 'On the menu': 'मेन्यू में', 'Removed': 'हटाए गए', 'Nothing has been removed.': 'कुछ हटाया नहीं गया है।', 'No services yet. Add what you offer so it can be billed and booked.': 'अभी कोई सर्विस नहीं। जो आप देते हैं उसे जोड़ें, ताकि बिल और बुकिंग हो सके।', 'New service': 'नई सर्विस', 'Service': 'सर्विस', 'Removed from the till': 'बिल से हटाई गई', 'For example Haircut': 'जैसे हेयरकट', 'How long it takes': 'कितना समय लगता है', 'Or type the minutes': 'या मिनट लिखें', 'Who it is for': 'किसके लिए', 'Anyone': 'कोई भी', 'Women': 'महिलाएँ', 'Men': 'पुरुष', 'Kids': 'बच्चे', 'A note for the team (optional)': 'टीम के लिए नोट (वैकल्पिक)', 'Add the service': 'सर्विस जोड़ें', 'Remove this service': 'यह सर्विस हटाएँ', 'Bring it back': 'वापस लाएँ', 'Remove this service?': 'यह सर्विस हटाएँ?', 'Which team member does it, and the products it uses, are set on the FlowXP website.': 'कौन सा सदस्य करता है और कौन से प्रोडक्ट लगते हैं, यह FlowXP वेबसाइट पर तय होता है।', 'Give the service a name': 'सर्विस का नाम लिखें', 'Enter how long it takes, in minutes (5 to 720)': 'कितना समय लगता है, मिनट में लिखें (5 से 720)',
  'Memberships and packages': 'मेंबरशिप और पैकेज', 'What you sell besides single services': 'अलग-अलग सर्विस के अलावा आप क्या बेचते हैं', 'No membership yet. A membership gives regular clients a discount or free services for a fee.': 'अभी कोई मेंबरशिप नहीं। मेंबरशिप में नियमित ग्राहकों को फ़ीस पर छूट या मुफ़्त सर्विस मिलती है।', 'No package yet. A package sells a bundle of visits at one price.': 'अभी कोई पैकेज नहीं। पैकेज में कई विज़िट एक दाम पर बिकती हैं।', 'New membership': 'नई मेंबरशिप', 'New package': 'नया पैकेज', 'Membership': 'मेंबरशिप', 'Package': 'पैकेज', 'For example Gold': 'जैसे गोल्ड', 'For example Bridal': 'जैसे ब्राइडल', 'How long it lasts': 'कितने समय चलता है', 'Or type the days': 'या दिन लिखें', '1 month': '1 महीना', '3 months': '3 महीने', '6 months': '6 महीने', '1 year': '1 साल', 'What members get': 'सदस्यों को क्या मिलता है', 'Discount (percent)': 'छूट (प्रतिशत)', 'For example 10': 'जैसे 10', 'The discount applies to': 'छूट किस पर लगेगी', 'Both': 'दोनों', 'Free services': 'मुफ़्त सर्विस', 'Search for a service to give free': 'मुफ़्त देने के लिए सर्विस खोजें', 'Priority booking': 'पहले बुकिंग', 'People who already have this membership keep the terms they bought. A change applies to new members.': 'जिनके पास यह मेंबरशिप पहले से है, उन्हें वही शर्तें मिलती रहेंगी। बदलाव नए सदस्यों पर लगेगा।', 'What is in it': 'इसमें क्या है', 'Each service, and how many visits': 'हर सर्विस, और कितनी विज़िट', 'Search for a service to add': 'जोड़ने के लिए सर्विस खोजें', 'People who already bought this package keep what they bought. A change applies to new sales.': 'जिन्होंने यह पैकेज पहले खरीदा है, उन्हें वही मिलेगा। बदलाव नई बिक्री पर लगेगा।', 'Add the membership': 'मेंबरशिप जोड़ें', 'Add the package': 'पैकेज जोड़ें', 'Give the plan a name': 'प्लान का नाम लिखें', 'Give the package a name': 'पैकेज का नाम लिखें', 'Enter how many days it lasts': 'कितने दिन चलता है, लिखें', 'The discount must be from 0 to 100 percent': 'छूट 0 से 100 प्रतिशत के बीच होनी चाहिए', 'Each free service needs a number of 1 or more': 'हर मुफ़्त सर्विस के लिए 1 या ज़्यादा लिखें', 'Give the plan something: a discount, free services or priority booking': 'प्लान में कुछ दें: छूट, मुफ़्त सर्विस या पहले बुकिंग', 'Add at least one service': 'कम से कम एक सर्विस जोड़ें', 'Each service needs a number of 1 or more': 'हर सर्विस के लिए 1 या ज़्यादा लिखें',
  'Beat order': 'बीट का क्रम', 'Suggest an order': 'क्रम सुझाएँ', 'Plan the day': 'दिन की योजना', 'The shops to visit, in order': 'जिन दुकानों पर जाना है, क्रम से', 'Visiting order': 'जाने का क्रम', 'Shops': 'दुकानें', 'Follow up': 'दोबारा मिलना है', "Shops you said you would visit again, not on this day's beat.": 'जिन दुकानों पर दोबारा जाने को कहा था, जो इस दिन की बीट में नहीं हैं।', 'No shops planned for this day. Beats are planned on the FlowXP website.': 'इस दिन के लिए कोई दुकान तय नहीं। बीट FlowXP वेबसाइट पर तय होती हैं।', 'No internet, and this day has not been saved on this phone yet. Open it once with the internet on.': 'इंटरनेट नहीं है, और यह दिन अभी इस फ़ोन में सहेजा नहीं गया। एक बार इंटरनेट चालू करके खोलें।', 'Move a shop up or down, or let FlowXP suggest an order: shops not yet visited first, then those who owe the most overdue money, then those who have not ordered for longest.': 'दुकान को ऊपर-नीचे करें, या FlowXP से क्रम सुझवाएँ: पहले जहाँ अभी नहीं गए, फिर जिनका सबसे ज़्यादा बकाया है, फिर जिन्होंने सबसे ज़्यादा समय से ऑर्डर नहीं दिया।', 'Offers for this shop': 'इस दुकान के ऑफ़र', 'No offer is running for this shop.': 'इस दुकान के लिए कोई ऑफ़र नहीं चल रहा।', 'No internet. Offers as they were {when}.': 'इंटरनेट नहीं। ऑफ़र वैसे ही जैसे {when} थे।',
  'Nothing yet. Tap an item on the menu.': 'अभी कुछ नहीं। मेन्यू से कोई आइटम दबाएँ।', 'On this order': 'इस ऑर्डर में', 'Not sent to the kitchen yet': 'अभी किचन को नहीं भेजा', 'Cooking': 'बन रहा है', 'Served': 'परोसा गया', 'on the bill': 'बिल में', 'added': 'जोड़ा गया',
  'Orders and ready dishes': 'ऑर्डर और तैयार डिश', 'Other alerts': 'दूसरे अलर्ट', 'Get alerts on this phone?': 'इस फ़ोन पर अलर्ट चाहिए?', 'FlowXP can tell you when a guest sends an order, when a dish is ready for your table, or when stock is running out. You can change this in Settings.': 'जब कोई मेहमान ऑर्डर भेजे, आपकी टेबल की डिश तैयार हो, या स्टॉक ख़त्म होने वाला हो, तब FlowXP आपको बता सकता है। इसे सेटिंग में बदल सकते हैं।', 'Turn on': 'चालू करें', 'No takeaway or delivery orders are open. Tap Takeaway order to start one.': 'कोई टेकअवे या डिलीवरी ऑर्डर खुला नहीं है। शुरू करने के लिए टेकअवे ऑर्डर दबाएँ।', 'Delete my account': 'मेरा खाता हटाएँ', 'Opens the FlowXP website, where you can delete your account or ask us to. Your business keeps its bills.': 'FlowXP वेबसाइट खुलेगी, जहाँ आप अपना खाता हटा सकते हैं या हमसे कह सकते हैं। आपके बिज़नेस के बिल सुरक्षित रहते हैं।', 'Alerts are off on this phone.': 'इस फ़ोन पर अलर्ट बंद हैं।', 'Alerts are on. Choose which ones on the FlowXP website, under Notifications.': 'अलर्ट चालू हैं। कौन-से चाहिए, यह FlowXP वेबसाइट पर नोटिफ़िकेशन में चुनें।', "Alerts are blocked for FlowXP in this phone's settings.": 'इस फ़ोन की सेटिंग में FlowXP के अलर्ट रोके हुए हैं।', 'Alerts are not available on this phone or in this build of the app.': 'इस फ़ोन पर या ऐप के इस वर्शन में अलर्ट उपलब्ध नहीं हैं।', 'Alerts on this phone': 'इस फ़ोन पर अलर्ट', 'A new order, a dish ready for your table, stock running out. Choose which ones on the FlowXP website, under Notifications.': 'नया ऑर्डर, आपकी टेबल की तैयार डिश, ख़त्म होता स्टॉक। कौन-से चाहिए, यह FlowXP वेबसाइट पर नोटिफ़िकेशन में चुनें।', 'Turn alerts off': 'अलर्ट बंद करें', 'Turn alerts on': 'अलर्ट चालू करें', "Open this phone's settings": 'फ़ोन की सेटिंग खोलें',
  'Enter a valid UPI ID, like shopname@okhdfcbank': 'सही UPI ID डालें, जैसे shopname@okhdfcbank', 'UPI ID saved. To check it, make a ₹1 bill and pay it with the QR code.': 'UPI ID सेव हो गई। जाँचने के लिए ₹1 का बिल बनाकर QR कोड से भुगतान करें।', 'UPI ID removed. The payment screen will not show a QR code.': 'UPI ID हटा दी गई। भुगतान स्क्रीन पर अब QR कोड नहीं दिखेगा।', 'Could not save the UPI ID.': 'UPI ID सेव नहीं हो सकी।', 'UPI ID': 'UPI ID', 'Customers who scan the QR on the payment screen pay to this UPI ID.': 'भुगतान स्क्रीन का QR स्कैन करने वाले ग्राहक इसी UPI ID पर भुगतान करते हैं।', 'No UPI ID yet. Add one and the payment screen shows a QR code customers can scan.': 'अभी कोई UPI ID नहीं है। जोड़ें, तो भुगतान स्क्रीन पर ग्राहकों के स्कैन के लिए QR कोड दिखेगा।', 'Not set': 'सेट नहीं है', 'Change UPI ID': 'UPI ID बदलें', 'Add UPI ID': 'UPI ID जोड़ें', 'Only the owner can change the UPI ID.': 'UPI ID सिर्फ़ मालिक बदल सकते हैं।', 'Leave it empty to remove the UPI ID.': 'UPI ID हटाने के लिए इसे ख़ाली छोड़ें।', "Printing with the phone's print screen.": 'फ़ोन की प्रिंट स्क्रीन से प्रिंट होगा।', 'Could not print.': 'प्रिंट नहीं हो सका।', 'Receipt printer': 'रसीद प्रिंटर', "Printing with the phone's print screen: it works with any printer the phone can reach (Wi-Fi, USB, or Bluetooth through the printer maker's app).": 'फ़ोन की प्रिंट स्क्रीन से प्रिंट: यह फ़ोन की पहुँच वाले किसी भी प्रिंटर (वाई-फ़ाई, USB, या प्रिंटर कंपनी के ऐप से ब्लूटूथ) के साथ चलता है।', 'Phone print screen': 'फ़ोन की प्रिंट स्क्रीन', 'Receipt paper width': 'रसीद के कागज़ की चौड़ाई', "Could not reach the printer, so the bill went to the phone's print screen instead.": 'प्रिंटर तक नहीं पहुँच सके, इसलिए बिल फ़ोन की प्रिंट स्क्रीन पर भेजा गया।',
  'Thermal printer (RawBT)': 'थर्मल प्रिंटर (RawBT)', 'Receipts now go to your thermal printer through RawBT. Print a test receipt to check it.': 'रसीदें अब RawBT से आपके थर्मल प्रिंटर पर जाएँगी। जाँचने के लिए टेस्ट रसीद प्रिंट करें।', "Could not use the thermal printer (is RawBT installed?), so the test went to the phone's print screen.": 'थर्मल प्रिंटर इस्तेमाल नहीं हो सका (क्या RawBT इंस्टॉल है?), इसलिए टेस्ट फ़ोन की प्रिंट स्क्रीन पर गया।', 'Sent to RawBT. If nothing prints, open RawBT and check that your printer is connected there.': 'RawBT को भेज दिया। कुछ प्रिंट न हो तो RawBT खोलकर जाँचें कि आपका प्रिंटर वहाँ जुड़ा है।', 'Printing straight to your thermal printer through the RawBT app.': 'RawBT ऐप से सीधे आपके थर्मल प्रिंटर पर प्रिंट हो रहा है।', 'One time: install the free RawBT app, switch your printer on, and connect it inside RawBT (Bluetooth or USB). After that, FlowXP prints to it with no questions.': 'एक बार: मुफ़्त RawBT ऐप इंस्टॉल करें, प्रिंटर चालू करें और उसे RawBT के अंदर जोड़ें (ब्लूटूथ या USB)। उसके बाद FlowXP बिना पूछे उसी पर प्रिंट करता है।', 'Get the RawBT app': 'RawBT ऐप पाएँ',
  "Could not use the thermal printer, so the bill went to the phone's print screen.": 'थर्मल प्रिंटर इस्तेमाल नहीं हो सका, इसलिए बिल फ़ोन की प्रिंट स्क्रीन पर गया।', 'Printed. Give it to the customer to scan, then confirm the money has arrived.': 'प्रिंट हो गया। ग्राहक को स्कैन के लिए दें, फिर पैसे आने की पुष्टि करें।', 'The bill is printed with a QR code for exactly {amount}. The customer scans the paper and their UPI app opens with the amount filled in.': 'बिल ठीक {amount} के QR कोड के साथ प्रिंट होता है। ग्राहक काग़ज़ को स्कैन करता है और उसका UPI ऐप रकम भरी हुई खुलता है।', 'Print the bill with the UPI QR': 'UPI QR के साथ बिल प्रिंट करें', 'This business has no UPI ID set up. Add one in Settings (the owner can), or take the payment another way.': 'इस बिज़नेस की UPI ID सेट नहीं है। सेटिंग में जोड़ें (मालिक जोड़ सकते हैं), या किसी और तरीक़े से भुगतान लें।',
  'Pay in full': 'पूरा भुगतान', 'Part payment': 'आंशिक भुगतान', 'Pay later': 'बाद में भुगतान', 'How much is being paid now?': 'अभी कितना भुगतान हो रहा है?', 'Paying now': 'अभी भुगतान', '{amount} stays due on {name}.': '{amount} {name} पर बाक़ी रहेगा।', 'The whole bill, {amount}, is left unpaid on {name}.': 'पूरा बिल, {amount}, {name} पर बिना भुगतान के रहेगा।', 'the customer': 'ग्राहक', 'Save the bill, {amount} unpaid': 'बिल सेव करें, {amount} बाक़ी', 'Take {now} now, {rest} stays due': 'अभी {now} लें, {rest} बाक़ी रहेगा', 'Take part payment': 'आंशिक भुगतान लें', 'Enter how much is being paid now.': 'दर्ज करें कि अभी कितना भुगतान हो रहा है।', 'Choose the customer first: the rest of the bill is owed by them.': 'पहले ग्राहक चुनें: बिल का बाक़ी हिस्सा उन पर बाक़ी रहेगा।', 'That is the whole bill. Choose Pay in full.': 'यह पूरा बिल है। पूरा भुगतान चुनें।',
};

/** Languages that have a dictionary. */
export const DICTS: Partial<Record<Lang, Record<string, string>>> = { hi: HI };
